In [1]:
import pandas as pd
data = [[1, '张三', '1999-3-10', 18],[2, '李四', '2002-3-10', 15],[3, '王五', '1990-3-10', 33],[4, '隔壁老王', '1983-3-10', 40]]

## 1 读写Excel

In [14]:
student_df = pd.DataFrame(data,columns=['id','name','birthday','age'])
# student_df.to_excel('out/students2.xlsx',index=False,header=False)
student_df.to_excel('out/students3.xlsx',index=False,sheet_name='学生信息表')

In [7]:
pd.read_excel('out/students.xlsx',index_col=0)

   id  name   birthday  age
0   1    张三  1999-3-10   18
1   2    李四  2002-3-10   15
2   3    王五  1990-3-10   33
3   4  隔壁老王  1983-3-10   40

In [13]:
pd.read_excel('out/students2.xlsx',header=None)

   0     1          2   3
0  1    张三  1999-3-10  18
1  2    李四  2002-3-10  15
2  3    王五  1990-3-10  33
3  4  隔壁老王  1983-3-10  40

In [22]:
df_dict = pd.read_excel('out/students3.xlsx',sheet_name=['学生信息表','表2'])
type(df_dict['表2'])

pandas.core.frame.DataFrame

## 2 读写CSV

In [25]:
student_df.to_csv('out/students2.csv',index=False,sep='\t')

In [24]:
pd.read_csv('out/students.csv')

   id  name   birthday  age
0   1    张三  1999-3-10   18
1   2    李四  2002-3-10   15
2   3    王五  1990-3-10   33
3   4  隔壁老王  1983-3-10   40

In [28]:
pd.read_csv('out/students2.csv',sep='\t')

   id  name   birthday  age
0   1    张三  1999-3-10   18
1   2    李四  2002-3-10   15
2   3    王五  1990-3-10   33
3   4  隔壁老王  1983-3-10   40

## 3 pandas 读写Mysql

In [31]:
from sqlalchemy import create_engine
# 创建数据库链接的engine
engine = create_engine('mysql+pymysql://root:root12345@localhost:3306/test1?charset=utf8')
student_df.to_sql('stu',engine,if_exists='append',index=False)

4

In [34]:
pd.read_sql('stu',engine.connect(),columns=['id','name'])

   id  name
0   1    张三
1   2    李四
2   3    王五
3   4  隔壁老王
4   1    张三
5   2    李四
6   3    王五
7   4  隔壁老王