In [1]:
import pandas as pd
df = pd.read_csv('C:/Develop/深圳42/data/LJdata.csv')

In [2]:
df.head()

      区域      地址    户型   面积    价格  朝向        更新时间  看房人数
0   燕莎租房     新源街  2室1厅   50  5800   南  2017.07.21    26
1   望京租房    澳洲康都  2室1厅   79  7800   东  2017.07.23    33
2  广安门租房    远见名苑  2室1厅   86  8000   东  2017.07.20    34
3  天通苑租房  天通苑北一区  2室1厅  103  5300  东南  2017.07.25    30
4  团结湖租房   团结湖北口  2室1厅   63  6400   南  2017.07.26    30

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2760 entries, 0 to 2759
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   区域      2760 non-null   object
 1   地址      2760 non-null   object
 2   户型      2760 non-null   object
 3   面积      2760 non-null   int64
 4   价格      2760 non-null   int64
 5   朝向      2760 non-null   object
 6   更新时间    2760 non-null   object
 7   看房人数    2760 non-null   int64
dtypes: int64(3), object(5)
memory usage: 172.6+ KB

In [4]:
df.describe()

                面积             价格         看房人数
count  2760.000000    2760.000000  2760.000000
mean     87.658696    7570.800725    13.448913
std      41.862928    6316.204986    12.746202
min      19.000000    1300.000000     0.000000
25%      58.000000    4500.000000     4.000000
50%      80.000000    6000.000000    10.000000
75%     103.000000    8500.000000    19.000000
max     720.000000  210000.000000   122.000000

In [8]:
要加载的列= ['区域','面积']
df[要加载的列]

         区域   面积
0      燕莎租房   50
1      望京租房   79
2     广安门租房   86
3     天通苑租房  103
4     团结湖租房   63
...     ...  ...
2755   朝青租房   50
2756  太阳宫租房   68
2757  六里桥租房   84
2758  陶然亭租房   91
2759  三元桥租房   62

[2760 rows x 2 columns]

In [99]:
df[['区域','面积']]

         区域   面积
0      燕莎租房   50
1      望京租房   79
2     广安门租房   86
3     天通苑租房  103
4     团结湖租房   63
...     ...  ...
2755   朝青租房   50
2756  太阳宫租房   68
2757  六里桥租房   84
2758  陶然亭租房   91
2759  三元桥租房   62

[2760 rows x 2 columns]

In [15]:
area_info = df['区域'].values

In [22]:
area_series = df['区域']
area_series.name

'区域'

In [18]:
pd.Series(area_info).to_frame()

          0
0      燕莎租房
1      望京租房
2     广安门租房
3     天通苑租房
4     团结湖租房
...     ...
2755   朝青租房
2756  太阳宫租房
2757  六里桥租房
2758  陶然亭租房
2759  三元桥租房

[2760 rows x 1 columns]

In [24]:
print(type(df[['区域']]))

<class 'pandas.core.frame.DataFrame'>

In [25]:
df[df['价格']==df['价格'].max()]

         区域      地址    户型   面积      价格 朝向        更新时间  看房人数
2658  和平里租房  雍和家园二期  6室3厅  720  210000  南  2017.07.26    21

In [26]:
df[df['价格']==df['价格'].min()]

        区域      地址    户型  面积    价格 朝向        更新时间  看房人数
2527  良乡租房  伟业嘉园西里  1室1厅  46  1300  南  2017.07.19    14

In [27]:
df[df['面积']==df['面积'].min()]

        区域      地址    户型  面积    价格  朝向        更新时间  看房人数
106  广安门租房  荣丰2008  1室0厅  19  3100  西南  2017.07.21    29

In [33]:
df[:10:2]

      区域     地址    户型  面积    价格 朝向        更新时间  看房人数
2  广安门租房   远见名苑  2室1厅  86  8000  东  2017.07.20    34
4  团结湖租房  团结湖北口  2室1厅  63  6400  南  2017.07.26    30

In [42]:
df[0:3]

      区域    地址    户型  面积    价格 朝向        更新时间  看房人数
0   燕莎租房   新源街  2室1厅  50  5800  南  2017.07.21    26
1   望京租房  澳洲康都  2室1厅  79  7800  东  2017.07.23    33
2  广安门租房  远见名苑  2室1厅  86  8000  东  2017.07.20    34

## loc 和 iloc

In [36]:
df.head()

      区域      地址    户型   面积    价格  朝向        更新时间  看房人数
0   燕莎租房     新源街  2室1厅   50  5800   南  2017.07.21    26
1   望京租房    澳洲康都  2室1厅   79  7800   东  2017.07.23    33
2  广安门租房    远见名苑  2室1厅   86  8000   东  2017.07.20    34
3  天通苑租房  天通苑北一区  2室1厅  103  5300  东南  2017.07.25    30
4  团结湖租房   团结湖北口  2室1厅   63  6400   南  2017.07.26    30

In [38]:
df.loc[0,'区域']

'燕莎租房'

In [39]:
df.loc[[0,1,2],['区域','地址','户型']]

      区域    地址    户型
0   燕莎租房   新源街  2室1厅
1   望京租房  澳洲康都  2室1厅
2  广安门租房  远见名苑  2室1厅

In [43]:
df.loc[0:3,'区域':'价格']

      区域      地址    户型   面积    价格
0   燕莎租房     新源街  2室1厅   50  5800
1   望京租房    澳洲康都  2室1厅   79  7800
2  广安门租房    远见名苑  2室1厅   86  8000
3  天通苑租房  天通苑北一区  2室1厅  103  5300

In [48]:
temp_df = df[:20:2]
temp_df.head()

      区域     地址    户型  面积    价格 朝向        更新时间  看房人数
0   燕莎租房    新源街  2室1厅  50  5800  南  2017.07.21    26
2  广安门租房   远见名苑  2室1厅  86  8000  东  2017.07.20    34
4  团结湖租房  团结湖北口  2室1厅  63  6400  南  2017.07.26    30
6   北苑租房    筑华年  3室1厅  89  7500  南  2017.07.25    29
8  小西天租房   今典花园  2室1厅  73  8500  西  2017.07.23    44

In [57]:
temp_df.loc[[2,4]]

      区域     地址    户型  面积    价格 朝向        更新时间  看房人数
2  广安门租房   远见名苑  2室1厅  86  8000  东  2017.07.20    34
4  团结湖租房  团结湖北口  2室1厅  63  6400  南  2017.07.26    30

In [59]:
temp_df.loc[:,'区域']

0      燕莎租房
2     广安门租房
4     团结湖租房
6      北苑租房
8     小西天租房
10    和平里租房
12    看丹桥租房
14     双井租房
16    紫竹桥租房
18     北苑租房
Name: 区域, dtype: object

In [58]:
temp_df.iloc[[1,2]]

      区域     地址    户型  面积    价格 朝向        更新时间  看房人数
2  广安门租房   远见名苑  2室1厅  86  8000  东  2017.07.20    34
4  团结湖租房  团结湖北口  2室1厅  63  6400  南  2017.07.26    30

In [60]:
df.iloc[:,1:5]

          地址    户型   面积     价格
0        新源街  2室1厅   50   5800
1       澳洲康都  2室1厅   79   7800
2       远见名苑  2室1厅   86   8000
3     天通苑北一区  2室1厅  103   5300
4      团结湖北口  2室1厅   63   6400
...      ...   ...  ...    ...
2755   天鹅湾北区  1室1厅   50   9500
2756     水星园  1室1厅   68   9500
2757    莲花小区  2室1厅   84   7200
2758  中海紫御公馆  2室2厅   91  12000
2759     曙光里  2室1厅   62   6200

[2760 rows x 4 columns]

- 区域是广安门租房的户型面积和价格

In [61]:
df.columns

Index(['区域', '地址', '户型', '面积', '价格', '朝向', '更新时间', '看房人数'], dtype='object')

In [69]:
df.loc[df['区域']=='广安门租房',['区域','户型', '面积', '价格']]

         区域    户型   面积     价格
2     广安门租房  2室1厅   86   8000
26    广安门租房  1室0厅   58   5600
30    广安门租房  1室0厅   58   5600
45    广安门租房  2室1厅   28   4800
48    广安门租房  1室1厅   40   3700
61    广安门租房  2室1厅   28   4800
64    广安门租房  1室1厅   40   3700
106   广安门租房  1室0厅   19   3100
128   广安门租房  1室1厅   28   4700
206   广安门租房  2室1厅  106   9000
214   广安门租房  2室1厅  106   9000
268   广安门租房  2室1厅   75   7500
272   广安门租房  2室1厅   75   7500
386   广安门租房  2室1厅   99   7600
766   广安门租房  1室0厅   25   3500
850   广安门租房  1室0厅   55   4800
971   广安门租房  2室1厅   98   9000
973   广安门租房  2室1厅   51   5500
978   广安门租房  2室1厅   87   8000
1117  广安门租房  2室1厅   68   5000
1143  广安门租房  2室1厅   57   5500
1155  广安门租房  2室1厅   54   5300
1188  广安门租房  2室1厅   68   5000
1409  广安门租房  2室1厅   50   4800
1415  广安门租房  2室1厅   50   4800
1481  广安门租房  3室2厅  144  14000
1483  广安门租房  3室1厅  124  11500
1499  广安门租房  1室0厅   48   5000
1664  广安门租房  1室1厅   52   5300
1754  广安门租房  3室1厅  132  11500
1790  广安门租房  3室2厅  159  13500
1806  广安门租房  3室2厅  159  13500
2238  广安门租房  2室1厅   50   6000
2349  广安门租房  1室0厅   55   5300
2444  广安门租房  2室1厅   57   4600
2716  广安门租房  2室1厅   86   8500

In [67]:
df[df['区域']=='广安门租房'].index

Int64Index([   2,   26,   30,   45,   48,   61,   64,  106,  128,  206,  214,
             268,  272,  386,  766,  850,  971,  973,  978, 1117, 1143, 1155,
            1188, 1409, 1415, 1481, 1483, 1499, 1664, 1754, 1790, 1806, 2238,
            2349, 2444, 2716],
           dtype='int64')

In [63]:
df.loc[:,'户型':'价格']

        户型   面积     价格
0     2室1厅   50   5800
1     2室1厅   79   7800
2     2室1厅   86   8000
3     2室1厅  103   5300
4     2室1厅   63   6400
...    ...  ...    ...
2755  1室1厅   50   9500
2756  1室1厅   68   9500
2757  2室1厅   84   7200
2758  2室2厅   91  12000
2759  2室1厅   62   6200

[2760 rows x 3 columns]

In [70]:
df.columns

Index(['区域', '地址', '户型', '面积', '价格', '朝向', '更新时间', '看房人数'], dtype='object')

In [75]:
df.iloc[(df['区域']=='广安门租房').to_list(),[0,2,3,4]]

         区域    户型   面积     价格
2     广安门租房  2室1厅   86   8000
26    广安门租房  1室0厅   58   5600
30    广安门租房  1室0厅   58   5600
45    广安门租房  2室1厅   28   4800
48    广安门租房  1室1厅   40   3700
61    广安门租房  2室1厅   28   4800
64    广安门租房  1室1厅   40   3700
106   广安门租房  1室0厅   19   3100
128   广安门租房  1室1厅   28   4700
206   广安门租房  2室1厅  106   9000
214   广安门租房  2室1厅  106   9000
268   广安门租房  2室1厅   75   7500
272   广安门租房  2室1厅   75   7500
386   广安门租房  2室1厅   99   7600
766   广安门租房  1室0厅   25   3500
850   广安门租房  1室0厅   55   4800
971   广安门租房  2室1厅   98   9000
973   广安门租房  2室1厅   51   5500
978   广安门租房  2室1厅   87   8000
1117  广安门租房  2室1厅   68   5000
1143  广安门租房  2室1厅   57   5500
1155  广安门租房  2室1厅   54   5300
1188  广安门租房  2室1厅   68   5000
1409  广安门租房  2室1厅   50   4800
1415  广安门租房  2室1厅   50   4800
1481  广安门租房  3室2厅  144  14000
1483  广安门租房  3室1厅  124  11500
1499  广安门租房  1室0厅   48   5000
1664  广安门租房  1室1厅   52   5300
1754  广安门租房  3室1厅  132  11500
1790  广安门租房  3室2厅  159  13500
1806  广安门租房  3室2厅  159  13500
2238  广安门租房  2室1厅   50   6000
2349  广安门租房  1室0厅   55   5300
2444  广安门租房  2室1厅   57   4600
2716  广安门租房  2室1厅   86   8500

In [74]:
(df['区域']=='广安门租房').to_list()

[False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 ...]

In [80]:
df.loc[(df['户型']=='2室1厅')&(df['朝向']=='南'),['区域','地址']]

         区域       地址
0      燕莎租房      新源街
4     团结湖租房    团结湖北口
7      马甸租房      月季园
11    健翔桥租房  华严北里中科院
21     望京租房  融科橄榄城三期
...     ...      ...
2661  石佛营租房      迎曦园
2669  紫竹桥租房     财智公馆
2671  紫竹桥租房     财智公馆
2708   劲松租房     劲松二区
2759  三元桥租房      曙光里

[242 rows x 2 columns]

In [81]:
df.columns

Index(['区域', '地址', '户型', '面积', '价格', '朝向', '更新时间', '看房人数'], dtype='object')

In [83]:
df.iloc[((df['户型']=='2室1厅')&(df['朝向']=='南')).to_list(),[0,1]]

         区域       地址
0      燕莎租房      新源街
4     团结湖租房    团结湖北口
7      马甸租房      月季园
11    健翔桥租房  华严北里中科院
21     望京租房  融科橄榄城三期
...     ...      ...
2661  石佛营租房      迎曦园
2669  紫竹桥租房     财智公馆
2671  紫竹桥租房     财智公馆
2708   劲松租房     劲松二区
2759  三元桥租房      曙光里

[242 rows x 2 columns]

In [84]:
df.query('区域=="回龙观租房"')

         区域         地址     户型   面积     价格   朝向        更新时间  看房人数
5     回龙观租房        龙华园   1室1厅   58   4000    南  2017.07.23    61
25    回龙观租房        佰嘉城   3室1厅  119   6300  南 北  2017.07.22    25
46    回龙观租房        龙华园   1室1厅   59   4000  南 北  2017.07.20    51
62    回龙观租房        龙华园   1室1厅   59   4000  南 北  2017.07.20    51
82    回龙观租房      风雅园三区   3室1厅  116   6100  南 北  2017.07.25     9
85    回龙观租房   首开国风美唐二期   2室2厅   96   7600  南 北  2017.07.22    13
135   回龙观租房        新龙城   2室1厅   90   5800   西南  2017.07.25    73
246   回龙观租房     流星花园三区   1室0厅   47   3800    南  2017.07.24    24
288   回龙观租房     流星花园三区   1室1厅   46   4000    南  2017.07.16    12
321   回龙观租房        龙华园   2室1厅   68   4700  南 北  2017.07.27     8
345   回龙观租房        新龙城   1室0厅   46   4100    北  2017.07.22    20
357   回龙观租房        龙回苑   3室1厅  116   6500  南 北  2017.07.18    18
362   回龙观租房        龙回苑   3室1厅  116   6500  南 北  2017.07.18    18
416   回龙观租房       万润家园   2室1厅   71   5000    北  2017.07.22    20
454   回龙观租房      风雅园三区   2室2厅   96   5000  南 北  2017.07.26    23
496   回龙观租房    龙城花园北二区   2室1厅   65   4600  南 北  2017.07.26    11
525   回龙观租房    龙城花园北二区   2室1厅   65   4600  南 北  2017.07.26    11
548   回龙观租房      龙腾苑二区   3室1厅  118   6800  南 北  2017.07.27    14
551   回龙观租房        通达园   2室1厅   96   5200  南 北  2017.07.24    17
600   回龙观租房      天露园二区   3室1厅  125   6500  南 北  2017.07.26     5
636   回龙观租房     东亚上北中心  2房间1卫   57   4200    西  2017.07.26    21
779   回龙观租房      龙腾苑四区   2室1厅   94   5000    南  2017.07.26     7
830   回龙观租房        慧华苑   1室1厅   48   3600    南  2017.07.25    11
847   回龙观租房        慧华苑   1室1厅   48   3600    南  2017.07.25    11
905   回龙观租房     龙城花园N区   5室2厅  217  14000  南 北  2017.07.26     7
947   回龙观租房     流星花园三区   1室1厅   72   5200    南  2017.07.24    14
1014  回龙观租房     北郊农场宿舍   2室1厅   65   4300  南 北  2017.07.26    19
1317  回龙观租房        天慧园   3室1厅  130   6700  南 北  2017.07.27     4
1352  回龙观租房        天慧园   3室1厅  130   6700  南 北  2017.07.27     4
1355  回龙观租房        新龙城   2室1厅   88   5700   西北  2017.07.25     5
1419  回龙观租房        龙回苑   3室1厅  126   5600  南 北  2017.07.27     2
1423  回龙观租房     北郊农场宿舍   2室1厅   65   4500  南 北  2017.07.26     6
1465  回龙观租房     北郊农场宿舍   2室1厅   79   4200  南 北  2017.07.20    13
1651  回龙观租房     流星花园三区   3室1厅  125   7500  南 北  2017.07.27    16
1673  回龙观租房  首开国风美唐综合楼  1房间1卫   46   4200    东  2017.07.26    35
1803  回龙观租房     田园风光雅苑   3室1厅  124   6700  南 北  2017.07.26     7
1918  回龙观租房      龙博苑三区   2室1厅   80   5800  南 北  2017.07.27     4
1932  回龙观租房      龙博苑三区   2室1厅   80   5800  南 北  2017.07.27     4
1990  回龙观租房     东亚上北中心  1房间1卫   38   3600    北  2017.07.27     8
2300  回龙观租房      云趣园三区   2室1厅   90   6200  南 北  2017.07.26     4
2344  回龙观租房       北京人家   1室1厅   56   4000    北  2017.07.27     6
2601  回龙观租房     东亚上北中心  1房间1卫   38   3700    北  2017.07.26    13

In [96]:
query_df= df.query('区域 in ["望京租房","天通苑租房","回龙观租房"]').query('朝向 in ["东","南"]')
query_df

         区域         地址     户型   面积     价格 朝向        更新时间  看房人数
1      望京租房       澳洲康都   2室1厅   79   7800  东  2017.07.23    33
5     回龙观租房        龙华园   1室1厅   58   4000  南  2017.07.23    61
20     望京租房      宝星园一区   4室2厅  217  15000  南  2017.07.23    32
21     望京租房    融科橄榄城三期   2室1厅   95  12000  南  2017.07.19    32
143    望京租房       澳洲康都   2室2厅   99   9000  南  2017.07.26    44
159    望京租房       澳洲康都   2室2厅   99   9000  南  2017.07.26    44
246   回龙观租房     流星花园三区   1室0厅   47   3800  南  2017.07.24    24
288   回龙观租房     流星花园三区   1室1厅   46   4000  南  2017.07.16    12
295   天通苑租房     天通西苑三区   2室1厅   96   5300  东  2017.07.25    15
324    望京租房       朝庭公寓   3室2厅  136  13500  南  2017.07.25    34
372    望京租房    北纬40度二期   2室1厅   86   8300  南  2017.07.20    25
434    望京租房    北纬40度二期   2室1厅   86   8300  南  2017.07.20    25
460    望京租房       望京新城   2室1厅   89   7800  南  2017.07.27    12
472    望京租房      金隅丽港城   2室2厅  105   9000  南  2017.07.15    17
635    望京租房      花家地小区   1室1厅   41   5500  南  2017.07.27     5
652    望京租房       星源国际   2室2厅  106  10000  东  2017.07.25     1
779   回龙观租房      龙腾苑四区   2室1厅   94   5000  南  2017.07.26     7
830   回龙观租房        慧华苑   1室1厅   48   3600  南  2017.07.25    11
847   回龙观租房        慧华苑   1室1厅   48   3600  南  2017.07.25    11
868    望京租房       望京新城   3室1厅  117  10000  南  2017.07.26    24
934   天通苑租房     天通苑北二区   2室2厅  119   5500  南  2017.07.26     0
947   回龙观租房     流星花园三区   1室1厅   72   5200  南  2017.07.24    14
988    望京租房     宝星国际二期   1室1厅   63   7000  南  2017.07.27    19
1632  天通苑租房    都市芳园锦湖园   4室3厅  237  15000  南  2017.07.24    12
1673  回龙观租房  首开国风美唐综合楼  1房间1卫   46   4200  东  2017.07.26    35
1706   望京租房    大西洋新城E区   2室1厅   81  12000  东  2017.07.22     0
1795   望京租房     华鼎世家一期   3室2厅  220  24000  南  2017.07.23     5
1811   望京租房     华鼎世家一期   3室2厅  220  24000  南  2017.07.23     5
1815   望京租房       利泽西园   2室1厅   98   7300  东  2017.07.26    13
1913   望京租房       夏都盈座   2室2厅   94  11500  南  2017.07.27     1
1919  天通苑租房     天通苑本六区   4室1厅  159   7500  南  2017.07.27     4
1933  天通苑租房     天通苑本六区   4室1厅  159   7500  南  2017.07.27     4
2196   望京租房     南湖东园二区   1室1厅   55   4500  东  2017.07.25     9
2468  天通苑租房     天通苑北一区   2室1厅   93   5500  南  2017.07.27     6
2505   望京租房       慧谷阳光   2室1厅   84   9300  南  2017.07.23    11

In [98]:
df.query('区域 in ["望京租房","天通苑租房","回龙观租房"] and 朝向 in ["东","南"]')

         区域         地址     户型   面积     价格 朝向        更新时间  看房人数
1      望京租房       澳洲康都   2室1厅   79   7800  东  2017.07.23    33
5     回龙观租房        龙华园   1室1厅   58   4000  南  2017.07.23    61
20     望京租房      宝星园一区   4室2厅  217  15000  南  2017.07.23    32
21     望京租房    融科橄榄城三期   2室1厅   95  12000  南  2017.07.19    32
143    望京租房       澳洲康都   2室2厅   99   9000  南  2017.07.26    44
159    望京租房       澳洲康都   2室2厅   99   9000  南  2017.07.26    44
246   回龙观租房     流星花园三区   1室0厅   47   3800  南  2017.07.24    24
288   回龙观租房     流星花园三区   1室1厅   46   4000  南  2017.07.16    12
295   天通苑租房     天通西苑三区   2室1厅   96   5300  东  2017.07.25    15
324    望京租房       朝庭公寓   3室2厅  136  13500  南  2017.07.25    34
372    望京租房    北纬40度二期   2室1厅   86   8300  南  2017.07.20    25
434    望京租房    北纬40度二期   2室1厅   86   8300  南  2017.07.20    25
460    望京租房       望京新城   2室1厅   89   7800  南  2017.07.27    12
472    望京租房      金隅丽港城   2室2厅  105   9000  南  2017.07.15    17
635    望京租房      花家地小区   1室1厅   41   5500  南  2017.07.27     5
652    望京租房       星源国际   2室2厅  106  10000  东  2017.07.25     1
779   回龙观租房      龙腾苑四区   2室1厅   94   5000  南  2017.07.26     7
830   回龙观租房        慧华苑   1室1厅   48   3600  南  2017.07.25    11
847   回龙观租房        慧华苑   1室1厅   48   3600  南  2017.07.25    11
868    望京租房       望京新城   3室1厅  117  10000  南  2017.07.26    24
934   天通苑租房     天通苑北二区   2室2厅  119   5500  南  2017.07.26     0
947   回龙观租房     流星花园三区   1室1厅   72   5200  南  2017.07.24    14
988    望京租房     宝星国际二期   1室1厅   63   7000  南  2017.07.27    19
1632  天通苑租房    都市芳园锦湖园   4室3厅  237  15000  南  2017.07.24    12
1673  回龙观租房  首开国风美唐综合楼  1房间1卫   46   4200  东  2017.07.26    35
1706   望京租房    大西洋新城E区   2室1厅   81  12000  东  2017.07.22     0
1795   望京租房     华鼎世家一期   3室2厅  220  24000  南  2017.07.23     5
1811   望京租房     华鼎世家一期   3室2厅  220  24000  南  2017.07.23     5
1815   望京租房       利泽西园   2室1厅   98   7300  东  2017.07.26    13
1913   望京租房       夏都盈座   2室2厅   94  11500  南  2017.07.27     1
1919  天通苑租房     天通苑本六区   4室1厅  159   7500  南  2017.07.27     4
1933  天通苑租房     天通苑本六区   4室1厅  159   7500  南  2017.07.27     4
2196   望京租房     南湖东园二区   1室1厅   55   4500  东  2017.07.25     9
2468  天通苑租房     天通苑北一区   2室1厅   93   5500  南  2017.07.27     6
2505   望京租房       慧谷阳光   2室1厅   84   9300  南  2017.07.23    11

In [91]:
query_df['朝向'].value_counts()

南    28
东     7
Name: 朝向, dtype: int64

In [93]:
df['朝向'].unique()

array(['南', '东', '东南', '西', '东 西', '西北', '东 东北', '南 北', '西 北', '东 北',
       '南 西', '西南', '北', '东北', '南 西 北', '东 南', '东 南 北', '东南 北', '东南 西北',
       '东 东南 南', '东 东南', '南 西北', '东 南 西', '东南 南', '南 西南', '东 西 北',
       '西南 东北', '西南 西', '东南 西南', '东 南 西 北', '西南 北', '东 西北', '东 西南',
       '东南 西', '东南 东北'], dtype=object)

In [95]:
df[(df['区域'].isin(["望京租房","天通苑租房","回龙观租房"])) &(df['朝向'].isin(["东","南"]))  ]

         区域         地址     户型   面积     价格 朝向        更新时间  看房人数
1      望京租房       澳洲康都   2室1厅   79   7800  东  2017.07.23    33
5     回龙观租房        龙华园   1室1厅   58   4000  南  2017.07.23    61
20     望京租房      宝星园一区   4室2厅  217  15000  南  2017.07.23    32
21     望京租房    融科橄榄城三期   2室1厅   95  12000  南  2017.07.19    32
143    望京租房       澳洲康都   2室2厅   99   9000  南  2017.07.26    44
159    望京租房       澳洲康都   2室2厅   99   9000  南  2017.07.26    44
246   回龙观租房     流星花园三区   1室0厅   47   3800  南  2017.07.24    24
288   回龙观租房     流星花园三区   1室1厅   46   4000  南  2017.07.16    12
295   天通苑租房     天通西苑三区   2室1厅   96   5300  东  2017.07.25    15
324    望京租房       朝庭公寓   3室2厅  136  13500  南  2017.07.25    34
372    望京租房    北纬40度二期   2室1厅   86   8300  南  2017.07.20    25
434    望京租房    北纬40度二期   2室1厅   86   8300  南  2017.07.20    25
460    望京租房       望京新城   2室1厅   89   7800  南  2017.07.27    12
472    望京租房      金隅丽港城   2室2厅  105   9000  南  2017.07.15    17
635    望京租房      花家地小区   1室1厅   41   5500  南  2017.07.27     5
652    望京租房       星源国际   2室2厅  106  10000  东  2017.07.25     1
779   回龙观租房      龙腾苑四区   2室1厅   94   5000  南  2017.07.26     7
830   回龙观租房        慧华苑   1室1厅   48   3600  南  2017.07.25    11
847   回龙观租房        慧华苑   1室1厅   48   3600  南  2017.07.25    11
868    望京租房       望京新城   3室1厅  117  10000  南  2017.07.26    24
934   天通苑租房     天通苑北二区   2室2厅  119   5500  南  2017.07.26     0
947   回龙观租房     流星花园三区   1室1厅   72   5200  南  2017.07.24    14
988    望京租房     宝星国际二期   1室1厅   63   7000  南  2017.07.27    19
1632  天通苑租房    都市芳园锦湖园   4室3厅  237  15000  南  2017.07.24    12
1673  回龙观租房  首开国风美唐综合楼  1房间1卫   46   4200  东  2017.07.26    35
1706   望京租房    大西洋新城E区   2室1厅   81  12000  东  2017.07.22     0
1795   望京租房     华鼎世家一期   3室2厅  220  24000  南  2017.07.23     5
1811   望京租房     华鼎世家一期   3室2厅  220  24000  南  2017.07.23     5
1815   望京租房       利泽西园   2室1厅   98   7300  东  2017.07.26    13
1913   望京租房       夏都盈座   2室2厅   94  11500  南  2017.07.27     1
1919  天通苑租房     天通苑本六区   4室1厅  159   7500  南  2017.07.27     4
1933  天通苑租房     天通苑本六区   4室1厅  159   7500  南  2017.07.27     4
2196   望京租房     南湖东园二区   1室1厅   55   4500  东  2017.07.25     9
2468  天通苑租房     天通苑北一区   2室1厅   93   5500  南  2017.07.27     6
2505   望京租房       慧谷阳光   2室1厅   84   9300  南  2017.07.23    11