In [1]:
import pandas as pd
df = pd.read_csv('C:/Develop/深圳42/data/LJdata.csv')

## 增加一列数据

In [3]:
df['城市'] = '北京'

In [6]:
temp_df = df.head()

In [8]:
temp_df['区县'] = ['朝阳区','朝阳区','西城区','昌平区','朝阳区']

C:\Users\Administrator\AppData\Local\Temp\ipykernel_12188\1930690445.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['区县'] = ['朝阳区','朝阳区','西城区','昌平区','朝阳区']

In [16]:
temp_df = df.head().copy()

In [17]:
temp_df

      区域      地址    户型   面积    价格  朝向        更新时间  看房人数  城市
0   燕莎租房     新源街  2室1厅   50  5800   南  2017.07.21    26  北京
1   望京租房    澳洲康都  2室1厅   79  7800   东  2017.07.23    33  北京
2  广安门租房    远见名苑  2室1厅   86  8000   东  2017.07.20    34  北京
3  天通苑租房  天通苑北一区  2室1厅  103  5300  东南  2017.07.25    30  北京
4  团结湖租房   团结湖北口  2室1厅   63  6400   南  2017.07.26    30  北京

In [18]:
temp_df['区县'] = ['朝阳区','朝阳区','西城区','昌平区','朝阳区']

In [20]:
temp_df['新价格'] = temp_df['价格']+1000

In [22]:
temp_df = df.head().copy()

In [24]:
temp_df.insert(loc=2,column='区县',value=['朝阳区','朝阳区','西城区','昌平区','朝阳区'])

In [26]:
temp_df['区县'].drop_duplicates()

0    朝阳区
2    西城区
3    昌平区
Name: 区县, dtype: object

In [29]:
df[['区域', '地址', '城市','户型', '面积', '价格', '朝向', '更新时间', '看房人数']]

         区域      地址  城市    户型   面积     价格  朝向        更新时间  看房人数
0      燕莎租房     新源街  北京  2室1厅   50   5800   南  2017.07.21    26
1      望京租房    澳洲康都  北京  2室1厅   79   7800   东  2017.07.23    33
2     广安门租房    远见名苑  北京  2室1厅   86   8000   东  2017.07.20    34
3     天通苑租房  天通苑北一区  北京  2室1厅  103   5300  东南  2017.07.25    30
4     团结湖租房   团结湖北口  北京  2室1厅   63   6400   南  2017.07.26    30
...     ...     ...  ..   ...  ...    ...  ..         ...   ...
2755   朝青租房   天鹅湾北区  北京  1室1厅   50   9500   南  2017.07.27    13
2756  太阳宫租房     水星园  北京  1室1厅   68   9500   北  2017.07.24    14
2757  六里桥租房    莲花小区  北京  2室1厅   84   7200  西南  2017.07.26     7
2758  陶然亭租房  中海紫御公馆  北京  2室2厅   91  12000   南  2017.07.26     6
2759  三元桥租房     曙光里  北京  2室1厅   62   6200   南  2017.07.25    19

[2760 rows x 9 columns]

In [28]:
df.columns

Index(['区域', '地址', '户型', '面积', '价格', '朝向', '更新时间', '看房人数', '城市'], dtype='object')

In [63]:
## DataFrame删除数据
temp_df = df.drop(area_list,axis=0)

In [59]:
area_list = df[df['区域']=='望京租房'].index.to_list()

In [64]:
temp_df[temp_df['区域']=='望京租房']

Empty DataFrame
Columns: [区域, 地址, 户型, 面积, 价格, 朝向, 更新时间, 看房人数]
Index: []

In [50]:
df[['面积','价格','看房人数']].max()

0        5800
1        7800
2        8000
3        5300
4        6400
        ...
2755     9500
2756     9500
2757     7200
2758    12000
2759     6200
Length: 2760, dtype: int64

In [67]:
df.shape[0]

2760

In [74]:
drop_dup_list = df.drop_duplicates().index.to_list()

In [85]:
# df.index[df.index.isin(drop_dup_list)==False]
drop_list = df.index[~df.index.isin(drop_dup_list)]

In [86]:
df.loc[drop_list]

              区域        地址    户型   面积     价格     朝向        更新时间  看房人数
30         广安门租房       朗琴园  1室0厅   58   5600      西  2017.07.25    30
60          望京租房   花家地西里一区  2室1厅   65   5800    南 北  2017.07.23    23
61         广安门租房    荣丰2008  2室1厅   28   4800      北  2017.07.21    39
62         回龙观租房       龙华园  1室1厅   59   4000    南 北  2017.07.20    51
63         安定门租房  安德路乙61号院  2室1厅   61   6800     东北  2017.07.27    30
...          ...       ...   ...  ...    ...    ...         ...   ...
2743        朝青租房    银谷美泉家园  3室2厅  142  13000    南 北  2017.07.24     6
2744        朝青租房      润枫水尚  2室1厅  121  10000    南 北  2017.07.21    34
2746    奥林匹克公园租房       京师园  3室1厅  147  14000    东 南  2017.07.20    13
2747        朝青租房     青年汇佳园  1室1厅   65   6300  南 西 北  2017.07.26    17
2748  九棵树(家乐福)租房       大方居  2室1厅   89   3100      西  2017.07.26     9

[379 rows x 8 columns]

In [79]:
df.loc[60]

区域            望京租房
地址         花家地西里一区
户型            2室1厅
面积              65
价格            5800
朝向             南 北
更新时间    2017.07.23
看房人数            23
Name: 60, dtype: object

In [81]:
df[(df['区域']=='望京租房')&(df['价格']==5800)]

        区域       地址    户型  面积    价格   朝向        更新时间  看房人数
44    望京租房  花家地西里一区  2室1厅  65  5800  南 北  2017.07.23    23
60    望京租房  花家地西里一区  2室1厅  65  5800  南 北  2017.07.23    23
254   望京租房     世安家园  1室1厅  62  5800   西南  2017.07.26    21
1722  望京租房    方舟苑二期  1室0厅  55  5800    北  2017.07.26     0

In [95]:
df.drop_duplicates(keep=False).loc[60]

KeyError: 60

In [87]:
df.drop_duplicates(subset=['户型','面积','价格'],keep='last')

         区域      地址    户型   面积     价格  朝向        更新时间  看房人数
0      燕莎租房     新源街  2室1厅   50   5800   南  2017.07.21    26
1      望京租房    澳洲康都  2室1厅   79   7800   东  2017.07.23    33
2     广安门租房    远见名苑  2室1厅   86   8000   东  2017.07.20    34
3     天通苑租房  天通苑北一区  2室1厅  103   5300  东南  2017.07.25    30
4     团结湖租房   团结湖北口  2室1厅   63   6400   南  2017.07.26    30
...     ...     ...   ...  ...    ...  ..         ...   ...
2755   朝青租房   天鹅湾北区  1室1厅   50   9500   南  2017.07.27    13
2756  太阳宫租房     水星园  1室1厅   68   9500   北  2017.07.24    14
2757  六里桥租房    莲花小区  2室1厅   84   7200  西南  2017.07.26     7
2758  陶然亭租房  中海紫御公馆  2室2厅   91  12000   南  2017.07.26     6
2759  三元桥租房     曙光里  2室1厅   62   6200   南  2017.07.25    19

[2106 rows x 8 columns]

## 数据修改

In [101]:
temp_df = df.head().copy()
temp_df

      区域      地址    户型   面积    价格  朝向        更新时间  看房人数
0   燕莎租房     新源街  2室1厅   50  5800   南  2017.07.21    26
1   望京租房    澳洲康都  2室1厅   79  7800   东  2017.07.23    33
2  广安门租房    远见名苑  2室1厅   86  8000   东  2017.07.20    34
3  天通苑租房  天通苑北一区  2室1厅  103  5300  东南  2017.07.25    30
4  团结湖租房   团结湖北口  2室1厅   63  6400   南  2017.07.26    30

In [102]:
temp_df['户型']='3室1厅'

In [104]:
temp_df.loc[0,'区域'] ='朝阳租房'

In [105]:
temp_df

      区域      地址    户型   面积    价格  朝向        更新时间  看房人数
0   朝阳租房     新源街  3室1厅   50  5800   南  2017.07.21    26
1   望京租房    澳洲康都  3室1厅   79  7800   东  2017.07.23    33
2  广安门租房    远见名苑  3室1厅   86  8000   东  2017.07.20    34
3  天通苑租房  天通苑北一区  3室1厅  103  5300  东南  2017.07.25    30
4  团结湖租房   团结湖北口  3室1厅   63  6400   南  2017.07.26    30

In [107]:
temp_df.iloc[2,1]='远见名苑小区'

In [108]:
temp_df

      区域      地址    户型   面积    价格  朝向        更新时间  看房人数
0   朝阳租房     新源街  3室1厅   50  5800   南  2017.07.21    26
1   望京租房    澳洲康都  3室1厅   79  7800   东  2017.07.23    33
2  广安门租房  远见名苑小区  3室1厅   86  8000   东  2017.07.20    34
3  天通苑租房  天通苑北一区  3室1厅  103  5300  东南  2017.07.25    30
4  团结湖租房   团结湖北口  3室1厅   63  6400   南  2017.07.26    30

In [116]:
temp_df.replace(to_replace='天通苑北1区',value='天通苑北二区',inplace=True)

In [117]:
temp_df

      区域      地址    户型   面积    价格  朝向        更新时间  看房人数
0   朝阳租房     新源街  3室1厅   50  5800   南  2017.07.21    26
1   望京租房    澳洲康都  3室1厅   79  7800   东  2017.07.23    33
2  广安门租房  远见名苑小区  3室1厅   86  8000   东  2017.07.20    34
3   昌平租房  天通苑北一区  3室1厅  103  5300  东南  2017.07.25    30
4  团结湖租房   团结湖北口  3室1厅   63  6400   南  2017.07.26    30

## apply 自定义函数

In [119]:
temp_df = df.head().copy()
temp_df

      区域      地址    户型   面积    价格  朝向        更新时间  看房人数
0   燕莎租房     新源街  2室1厅   50  5800   南  2017.07.21    26
1   望京租房    澳洲康都  2室1厅   79  7800   东  2017.07.23    33
2  广安门租房    远见名苑  2室1厅   86  8000   东  2017.07.20    34
3  天通苑租房  天通苑北一区  2室1厅  103  5300  东南  2017.07.25    30
4  团结湖租房   团结湖北口  2室1厅   63  6400   南  2017.07.26    30

In [132]:
def func(area_str,arg1,arg2):
    print('调用了func方法====',area_str)
    if area_str =='广安门租房':
        return arg1
    elif area_str =='天通苑租房':
        return arg2
    else:
        return area_str

In [126]:
result_list = []
for area_str in temp_df['区域'].to_list():
    result_list.append(func(area_str))

In [128]:
pd.Series(result_list,name='区域')

0     燕莎租房
1     望京租房
2     西城租房
3     昌平租房
4    团结湖租房
Name: 区域, dtype: object

In [133]:
temp_df['区域'].apply(func,args=('西城租房','昌平租房'))

调用了func方法==== 燕莎租房
调用了func方法==== 望京租房
调用了func方法==== 广安门租房
调用了func方法==== 天通苑租房
调用了func方法==== 团结湖租房

0     燕莎租房
1     望京租房
2     西城租房
3     昌平租房
4    团结湖租房
Name: 区域, dtype: object

In [136]:
from pandas import DataFrame
temp_df2:DataFrame = temp_df.iloc[:,0:5].copy()

In [137]:
temp_df2

      区域      地址    户型   面积    价格
0   燕莎租房     新源街  2室1厅   50  5800
1   望京租房    澳洲康都  2室1厅   79  7800
2  广安门租房    远见名苑  2室1厅   86  8000
3  天通苑租房  天通苑北一区  2室1厅  103  5300
4  团结湖租房   团结湖北口  2室1厅   63  6400

In [154]:
s_row = temp_df2.loc[0]
s_row['户型']

'2室1厅'

In [179]:
temp_df2

      区域      地址    户型   面积    价格
0   燕莎租房     新源街  2室1厅   50  5800
1   望京租房    澳洲康都  2室1厅   79  7800
2  广安门租房    远见名苑  2室1厅   86  8000
3  天通苑租房  天通苑北一区  2室1厅  103  5300
4  团结湖租房   团结湖北口  2室1厅   63  6400

In [187]:
def func1(s):
    if s['区域'] == '望京租房':
        s['户型']='1室1厅'
    elif s['区域'] == '天通苑租房':
        s['户型']='3室1厅'
    return s

In [158]:
temp_df2.apply(func1,axis=1)

      区域      地址    户型   面积    价格
0   燕莎租房     新源街  2室1厅   50  5800
1   望京租房    澳洲康都  1室1厅   79  7800
2  广安门租房    远见名苑  2室1厅   86  8000
3  天通苑租房  天通苑北一区  3室1厅  103  5300
4  团结湖租房   团结湖北口  2室1厅   63  6400

In [199]:
# 创建一个空白的DataFrame用于保存结果
result_df = pd.DataFrame()
# 遍历行索引
for ind in temp_df2.index:
    # 获取了每一行数据
    s = temp_df2.loc[ind]
    # 通过自定义函数, 对每一行数据进行处理
    s = func1(s)
    # 处理之后的series 添加到dataFrame
    result_df =result_df.append(s)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_12188\2912801782.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df =result_df.append(s)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_12188\3178412432.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s['户型']='1室1厅'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_12188\2912801782.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df =result_df.append(s)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_12188\2912801782.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df =result_df.append(s)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_12188\3178412432.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s['户型']='3室1厅'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_12188\2912801782.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df =result_df.append(s)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_12188\2912801782.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df =result_df.append(s)

In [200]:
result_df

      区域      地址    户型   面积    价格
0   燕莎租房     新源街  2室1厅   50  5800
1   望京租房    澳洲康都  1室1厅   79  7800
2  广安门租房    远见名苑  2室1厅   86  8000
3  天通苑租房  天通苑北一区  3室1厅  103  5300
4  团结湖租房   团结湖北口  2室1厅   63  6400

In [162]:
def func2(s):
    # print(s)
    # print('=======',s.name)
    if s.name=='地址':
        return s+'小区'
    elif s.name=='面积':
        return s/2
    else:
        return s

In [163]:
temp_df2.apply(func2)

      区域        地址    户型    面积    价格
0   燕莎租房     新源街小区  2室1厅  25.0  5800
1   望京租房    澳洲康都小区  2室1厅  39.5  7800
2  广安门租房    远见名苑小区  2室1厅  43.0  8000
3  天通苑租房  天通苑北一区小区  2室1厅  51.5  5300
4  团结湖租房   团结湖北口小区  2室1厅  31.5  6400

In [150]:
temp_df2.apply(func1,axis=1)

区域    燕莎租房
地址     新源街
户型    2室1厅
面积      50
价格    5800
Name: 0, dtype: object
============== <class 'pandas.core.series.Series'>
区域    望京租房
地址    澳洲康都
户型    2室1厅
面积      79
价格    7800
Name: 1, dtype: object
============== <class 'pandas.core.series.Series'>
区域    广安门租房
地址     远见名苑
户型     2室1厅
面积       86
价格     8000
Name: 2, dtype: object
============== <class 'pandas.core.series.Series'>
区域     天通苑租房
地址    天通苑北一区
户型      2室1厅
面积       103
价格      5300
Name: 3, dtype: object
============== <class 'pandas.core.series.Series'>
区域    团结湖租房
地址    团结湖北口
户型     2室1厅
面积       63
价格     6400
Name: 4, dtype: object
============== <class 'pandas.core.series.Series'>

0    None
1    None
2    None
3    None
4    None
dtype: object

In [165]:
def func1(s,arg1,arg2):
    if s['区域'] == '望京租房':
        s['户型']=arg1
    elif s['区域'] == '天通苑租房':
        s['户型']=arg2
    return s
temp_df2.apply(func1,axis=1,args=('1室0厅','3室1厅'))

      区域      地址    户型   面积    价格
0   燕莎租房     新源街  2室1厅   50  5800
1   望京租房    澳洲康都  1室0厅   79  7800
2  广安门租房    远见名苑  2室1厅   86  8000
3  天通苑租房  天通苑北一区  3室1厅  103  5300
4  团结湖租房   团结湖北口  2室1厅   63  6400

In [167]:
def func3(value):
    print(value)
    print('=======apply map =========')
    if value=='天通苑租房':
        return '昌平租房'
    elif value ==8000:
        return value+500
    else:
        return value
temp_df2.applymap(func3)

燕莎租房
=======apply map =========
望京租房
=======apply map =========
广安门租房
=======apply map =========
天通苑租房
=======apply map =========
团结湖租房
=======apply map =========
新源街
=======apply map =========
澳洲康都
=======apply map =========
远见名苑
=======apply map =========
天通苑北一区
=======apply map =========
团结湖北口
=======apply map =========
2室1厅
=======apply map =========
2室1厅
=======apply map =========
2室1厅
=======apply map =========
2室1厅
=======apply map =========
2室1厅
=======apply map =========
50
=======apply map =========
79
=======apply map =========
86
=======apply map =========
103
=======apply map =========
63
=======apply map =========
5800
=======apply map =========
7800
=======apply map =========
8000
=======apply map =========
5300
=======apply map =========
6400
=======apply map =========

      区域      地址    户型   面积    价格
0   燕莎租房     新源街  2室1厅   50  5800
1   望京租房    澳洲康都  2室1厅   79  7800
2  广安门租房    远见名苑  2室1厅   86  8500
3   昌平租房  天通苑北一区  2室1厅  103  5300
4  团结湖租房   团结湖北口  2室1厅   63  6400

In [170]:
area_series = temp_df['区域']

In [175]:
print(area_series)

0     燕莎租房
1     望京租房
2    广安门租房
3    天通苑租房
4    团结湖租房
Name: 区域, dtype: object

In [177]:
area_list = temp_df['区域'].to_list()
print(pd.Series(area_list,name='区域'))

0     燕莎租房
1     望京租房
2    广安门租房
3    天通苑租房
4    团结湖租房
Name: 区域, dtype: object

In [178]:
area_series.name

'区域'

In [201]:
# 自定义函数
def test_func(s):
    print(s)

# 调用自定义函数的方法 第一个参数函数对象, 第二个参数就是自定义函数要接受的参数
def apply_test(func,arg1):
    func(arg1)
# 执行调用自定义函数的方法
apply_test(test_func,'你好')

你好