In [1]:
import pandas as pd
df = pd.read_csv('C:/Develop/深圳42/data/LJdata.csv')

## 访问行索引和列名

In [5]:
df.head()

      区域      地址    户型   面积    价格  朝向        更新时间  看房人数
0   燕莎租房     新源街  2室1厅   50  5800   南  2017.07.21    26
1   望京租房    澳洲康都  2室1厅   79  7800   东  2017.07.23    33
2  广安门租房    远见名苑  2室1厅   86  8000   东  2017.07.20    34
3  天通苑租房  天通苑北一区  2室1厅  103  5300  东南  2017.07.25    30
4  团结湖租房   团结湖北口  2室1厅   63  6400   南  2017.07.26    30

In [2]:
df.index

RangeIndex(start=0, stop=2760, step=1)

In [3]:
df.columns

Index(['区域', '地址', '户型', '面积', '价格', '朝向', '更新时间', '看房人数'], dtype='object')

In [9]:
# 修改索引   某一列的值设置为index
df.set_index('地址', inplace=True)

In [18]:
df.reset_index(inplace=True)

ValueError: cannot insert level_0, already exists

In [19]:
df.columns

Index(['level_0', 'index', '地址', '区域', '户型', '面积', '价格', '朝向', '更新时间', '看房人数'], dtype='object')

In [22]:
df.drop(['level_0', 'index'],axis=1,inplace=True)

In [25]:
# 修改列名
df.index[0] = 10

TypeError: Index does not support mutable operations

In [28]:
df.columns[0] ='address'

TypeError: Index does not support mutable operations

In [32]:
df.columns = ['address', '区域', '户型', '面积', '价格', '朝向', '更新时间', '看房人数']
df

     address     区域    户型   面积     价格  朝向        更新时间  看房人数
0        新源街   燕莎租房  2室1厅   50   5800   南  2017.07.21    26
1       澳洲康都   望京租房  2室1厅   79   7800   东  2017.07.23    33
2       远见名苑  广安门租房  2室1厅   86   8000   东  2017.07.20    34
3     天通苑北一区  天通苑租房  2室1厅  103   5300  东南  2017.07.25    30
4      团结湖北口  团结湖租房  2室1厅   63   6400   南  2017.07.26    30
...      ...    ...   ...  ...    ...  ..         ...   ...
2755   天鹅湾北区   朝青租房  1室1厅   50   9500   南  2017.07.27    13
2756     水星园  太阳宫租房  1室1厅   68   9500   北  2017.07.24    14
2757    莲花小区  六里桥租房  2室1厅   84   7200  西南  2017.07.26     7
2758  中海紫御公馆  陶然亭租房  2室2厅   91  12000   南  2017.07.26     6
2759     曙光里  三元桥租房  2室1厅   62   6200   南  2017.07.25    19

[2760 rows x 8 columns]

In [33]:
temp_df = df.head().copy()
temp_df

  address     区域    户型   面积    价格  朝向        更新时间  看房人数
0     新源街   燕莎租房  2室1厅   50  5800   南  2017.07.21    26
1    澳洲康都   望京租房  2室1厅   79  7800   东  2017.07.23    33
2    远见名苑  广安门租房  2室1厅   86  8000   东  2017.07.20    34
3  天通苑北一区  天通苑租房  2室1厅  103  5300  东南  2017.07.25    30
4   团结湖北口  团结湖租房  2室1厅   63  6400   南  2017.07.26    30

In [34]:
temp_df.index=['a','b','c','d','e']

In [36]:
temp_df.index[0] = 'A'

TypeError: Index does not support mutable operations

In [ ]:
# rename方法

In [41]:
temp_df.rename(index={'a':'A'},columns={'address':'地址'},inplace=True)

In [42]:
temp_df

       地址     区域    户型   面积    价格  朝向        更新时间  看房人数
A     新源街   燕莎租房  2室1厅   50  5800   南  2017.07.21    26
b    澳洲康都   望京租房  2室1厅   79  7800   东  2017.07.23    33
c    远见名苑  广安门租房  2室1厅   86  8000   东  2017.07.20    34
d  天通苑北一区  天通苑租房  2室1厅  103  5300  东南  2017.07.25    30
e   团结湖北口  团结湖租房  2室1厅   63  6400   南  2017.07.26    30

In [48]:
df = pd.read_csv('C:/Develop/深圳42/data/LJdata.csv')
df

         区域      地址    户型   面积     价格  朝向        更新时间  看房人数
0      燕莎租房     新源街  2室1厅   50   5800   南  2017.07.21    26
1      望京租房    澳洲康都  2室1厅   79   7800   东  2017.07.23    33
2     广安门租房    远见名苑  2室1厅   86   8000   东  2017.07.20    34
3     天通苑租房  天通苑北一区  2室1厅  103   5300  东南  2017.07.25    30
4     团结湖租房   团结湖北口  2室1厅   63   6400   南  2017.07.26    30
...     ...     ...   ...  ...    ...  ..         ...   ...
2755   朝青租房   天鹅湾北区  1室1厅   50   9500   南  2017.07.27    13
2756  太阳宫租房     水星园  1室1厅   68   9500   北  2017.07.24    14
2757  六里桥租房    莲花小区  2室1厅   84   7200  西南  2017.07.26     7
2758  陶然亭租房  中海紫御公馆  2室2厅   91  12000   南  2017.07.26     6
2759  三元桥租房     曙光里  2室1厅   62   6200   南  2017.07.25    19

[2760 rows x 8 columns]

In [52]:
# 读数据的时候直接指定哪一列作为索引
df = pd.read_csv('C:/Develop/深圳42/data/LJdata.csv',index_col='地址')
df.reset_index()

          地址     区域    户型   面积     价格  朝向        更新时间  看房人数
0        新源街   燕莎租房  2室1厅   50   5800   南  2017.07.21    26
1       澳洲康都   望京租房  2室1厅   79   7800   东  2017.07.23    33
2       远见名苑  广安门租房  2室1厅   86   8000   东  2017.07.20    34
3     天通苑北一区  天通苑租房  2室1厅  103   5300  东南  2017.07.25    30
4      团结湖北口  团结湖租房  2室1厅   63   6400   南  2017.07.26    30
...      ...    ...   ...  ...    ...  ..         ...   ...
2755   天鹅湾北区   朝青租房  1室1厅   50   9500   南  2017.07.27    13
2756     水星园  太阳宫租房  1室1厅   68   9500   北  2017.07.24    14
2757    莲花小区  六里桥租房  2室1厅   84   7200  西南  2017.07.26     7
2758  中海紫御公馆  陶然亭租房  2室2厅   91  12000   南  2017.07.26     6
2759     曙光里  三元桥租房  2室1厅   62   6200   南  2017.07.25    19

[2760 rows x 8 columns]