In [2]:
import pandas as pd
import numpy as np

## 1 通过Numpy的Ndarray 创建一个Series

In [4]:
n1 = np.array([1,2,3])
type(n1)

numpy.ndarray

In [8]:
# 创建一个Series对象
s =pd.Series(n1)
type(s)

pandas.core.series.Series

In [9]:
# 我们在创建Series的时候, 如果不指定索引, Pandas也会自动帮助我们添加一个索引
# 默认加的索引是从0开始的整数  RangeIndex
s.index

RangeIndex(start=0, stop=3, step=1)

In [36]:
s1 = pd.Series(n1,index=['a','b','c'])
s1.index

Index(['a', 'b', 'c'], dtype='object')

In [13]:
s1

a    1
b    2
c    3
dtype: int32

## 2 通过列表创建Series

In [17]:
s3 = pd.Series(['香蕉','apple',2],index=[1,2,3])

In [18]:
s3.index

Int64Index([1, 2, 3], dtype='int64')

In [28]:
data_dict = {'Age':18,'Name':'Tom','Job':'大数据工程师'}
s4 = pd.Series(data_dict)

In [23]:
s4.values

array([18, 'Tom', '大数据工程师'], dtype=object)

## Series的常用属性

In [25]:
s4

Age         18
Name       Tom
Job     大数据工程师
dtype: object

In [24]:
s4.shape

(3,)

In [33]:
data_dict = {'Age':18,'Name':'Tom'}
s4 = pd.Series(data_dict)
s4.shape

(2,)

In [29]:
s4.size

3

In [37]:
s1.dtype

dtype('int32')

## 常用方法

In [57]:
s5 = pd.Series([1, 2, 3, 4, 5,6,7,8,100])

In [42]:
s5.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [44]:
s5.tail(6)

3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [47]:
s4.keys()

Index(['Age', 'Name'], dtype='object')

In [48]:
s5.to_list()

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
s5.to_frame()

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9

In [50]:
s5

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [54]:
s5.mean()

5.0

In [58]:
s5.describe()

count      9.000000
mean      15.111111
std       31.915688
min        1.000000
25%        3.000000
50%        5.000000
75%        7.000000
max      100.000000
dtype: float64

In [ ]:
# 方差 =  ∑(每一个值 - 平均值)²/总数   标准差 = 方差开根号

In [74]:
s1 = pd.Series([1,1,2,2,3,3,3,4,5,6,7,8,9])
s1.head()

0    1
1    1
2    2
3    2
4    3
dtype: int64

In [75]:
s1.shape

(13,)

In [62]:
s1.drop_duplicates(inplace=True)

In [63]:
s1

0     1
2     2
4     3
7     4
8     5
9     6
10    7
11    8
12    9
dtype: int64

In [67]:
s1.sort_values(ascending=False,inplace=True)

In [68]:
s1

12    9
11    8
10    7
9     6
8     5
7     4
4     3
2     2
0     1
dtype: int64

In [70]:
s1.sort_index(inplace=True)

In [71]:
s1

0     1
2     2
4     3
7     4
8     5
9     6
10    7
11    8
12    9
dtype: int64

In [78]:
type(s1.unique())

numpy.ndarray

In [77]:
s1.nunique()

9

In [80]:
s1.value_counts()

3    3
1    2
2    2
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int64

## 通过布尔值列表(布尔索引)获取部分数据

In [82]:
df = pd.read_csv('C:/Develop/深圳42/data/scientists.csv')
df.head()

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56     Biologist

In [89]:
df

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [111]:
df['Name'][df['Occupation']=='Chemist']

0    Rosaline Franklin
3          Marie Curie
Name: Name, dtype: object

In [91]:
df['Age']

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [88]:
df['Age'].mean()

59.125

In [104]:
boolean_list = (df['Age']>df['Age'].mean()).to_list()
boolean_s = df['Age']>df['Age'].mean()

In [105]:
df['Name'][boolean_s]

1          William Gosset
2    Florence Nightingale
3             Marie Curie
7            Johann Gauss
Name: Name, dtype: object

In [106]:
df['Name'][df['Age']>df['Age'].mean()]

1          William Gosset
2    Florence Nightingale
3             Marie Curie
7            Johann Gauss
Name: Name, dtype: object

In [107]:
df['Name']

0       Rosaline Franklin
1          William Gosset
2    Florence Nightingale
3             Marie Curie
4           Rachel Carson
5               John Snow
6             Alan Turing
7            Johann Gauss
Name: Name, dtype: object

In [108]:
boolean_list

[False, True, True, True, False, False, False, True]

In [110]:
df['Name'][[False, True, True, True, False, False, False, True,False]]

IndexError: Boolean index has wrong length: 9 instead of 8

In [123]:
df['Name'][df['Age']>df['Age'].mean()][df['Occupation']=='Chemist']

3    Marie Curie
Name: Name, dtype: object

In [132]:
df['Name'][(df['Age']>df['Age'].mean()) or (df['Occupation']=='Chemist')]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [128]:
True and False

False

In [137]:
df['Name'][(df['Age']>df['Age'].mean()) & (df['Occupation']=='Chemist')]

3    Marie Curie
Name: Name, dtype: object

In [126]:
df['Age']>df['Age'].mean()

0    False
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: Age, dtype: bool

## Series的运算

In [138]:
df['Occupation']=='Chemist'

0     True
1    False
2    False
3     True
4    False
5    False
6    False
7    False
Name: Occupation, dtype: bool

In [139]:
df['Age']+10

0     47
1     71
2    100
3     76
4     66
5     55
6     51
7     87
Name: Age, dtype: int64

In [142]:
age_list = df['Age'].to_list()

[37, 61, 90, 66, 56, 45, 41, 77, 37, 61, 90, 66, 56, 45, 41, 77]

In [145]:
df['Name']

0       Rosaline Franklin10
1          William Gosset10
2    Florence Nightingale10
3             Marie Curie10
4           Rachel Carson10
5               John Snow10
6             Alan Turing10
7            Johann Gauss10
Name: Name, dtype: object

In [149]:
df['Age']

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [148]:
df['Age'].sort_values(ascending=False)

2    90
7    77
3    66
1    61
4    56
5    45
6    41
0    37
Name: Age, dtype: int64

In [150]:
df['Age'].sort_index(ascending=False)+df['Age']

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [153]:
df['Age'] +pd.Series({10:1,11:3,12:5})

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
10   NaN
11   NaN
12   NaN
dtype: float64

In [156]:
s = pd.Series([1,2,3,4,5,6,6,6])
s = s.drop_duplicates()

In [157]:
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

## DataFrame的创建

### 通过字典创建

In [165]:
dict_data = {'id':[1,2,3],'name':['张三','李四','Apple'],'age':[21,22,23]}
df = pd.DataFrame(dict_data,columns=['id','age','name'],index=['a','b','c'])
df

   id  age   name
a   1   21     张三
b   2   22     李四
c   3   23  Apple

### 通过列表[元组] 列表[列表] 方式创建

In [173]:
list_data =[
    (1,'张三',21),
    (2,'李四',22),
    (3,'王五',23)
            ]
df = pd.DataFrame(list_data,columns=['id','age','name'])
df

   id age  name
0   1  张三    21
1   2  李四    22
2   3  王五    23

In [176]:
df.shape

(3, 3)

In [177]:
df.shape[0]

3

In [178]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [179]:
df.columns

Index(['id', 'age', 'name'], dtype='object')

In [181]:
print(df.values)

[[1 '张三' 21]
 [2 '李四' 22]
 [3 '王五' 23]]

In [182]:
type(df.values)

numpy.ndarray

In [184]:
df_sci = pd.read_csv('C:/Develop/深圳42/data/scientists.csv')
df_sci.head()

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56     Biologist

In [185]:
df_sci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Born        8 non-null      object
 2   Died        8 non-null      object
 3   Age         8 non-null      int64
 4   Occupation  8 non-null      object
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes

In [186]:
df_sci.describe()

             Age
count   8.000000
mean   59.125000
std    18.325918
min    37.000000
25%    44.000000
50%    58.500000
75%    68.750000
max    90.000000

In [187]:
df_sci.describe(include='object')

                     Name        Born        Died Occupation
count                   8           8           8          8
unique                  8           8           8          7
top     Rosaline Franklin  1920-07-25  1958-04-16    Chemist
freq                    1           1           1          2

In [188]:
df_sci.describe(include='all')

                     Name        Born        Died        Age Occupation
count                   8           8           8   8.000000          8
unique                  8           8           8        NaN          7
top     Rosaline Franklin  1920-07-25  1958-04-16        NaN    Chemist
freq                    1           1           1        NaN          2
mean                  NaN         NaN         NaN  59.125000        NaN
std                   NaN         NaN         NaN  18.325918        NaN
min                   NaN         NaN         NaN  37.000000        NaN
25%                   NaN         NaN         NaN  44.000000        NaN
50%                   NaN         NaN         NaN  58.500000        NaN
75%                   NaN         NaN         NaN  68.750000        NaN
max                   NaN         NaN         NaN  90.000000        NaN

In [192]:
df_sci.sort_values('Age',ascending=False)

                   Name        Born        Died  Age          Occupation
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist

In [193]:
df_sci['Occupation'].value_counts()

Chemist               2
Statistician          1
Nurse                 1
Biologist             1
Physician             1
Computer Scientist    1
Mathematician         1
Name: Occupation, dtype: int64

In [195]:
df_sci.sort_index(ascending=False)

                   Name        Born        Died  Age          Occupation
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
5             John Snow  1813-03-15  1858-06-16   45           Physician
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist

In [197]:
df_sci['Name'][df_sci['Age']>df_sci['Age'].mean()]

1          William Gosset
2    Florence Nightingale
3             Marie Curie
7            Johann Gauss
Name: Name, dtype: object

In [198]:
df_sci[df_sci['Age']>df_sci['Age'].mean()]

                   Name        Born        Died  Age     Occupation
1        William Gosset  1876-06-13  1937-10-16   61   Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90          Nurse
3           Marie Curie  1867-11-07  1934-07-04   66        Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77  Mathematician

## DataFrame 的计算

In [199]:
df_sci * 2

,Name,Born,Died,Age,Occupation
0,Rosaline FranklinRosaline Franklin,1920-07-251920-07-25,1958-04-161958-04-16,74,ChemistChemist
1,William GossetWilliam Gosset,1876-06-131876-06-13,1937-10-161937-10-16,122,StatisticianStatistician
2,Florence NightingaleFlorence Nightingale,1820-05-121820-05-12,1910-08-131910-08-13,180,NurseNurse
3,Marie CurieMarie Curie,1867-11-071867-11-07,1934-07-041934-07-04,132,ChemistChemist
4,Rachel CarsonRachel Carson,1907-05-271907-05-27,1964-04-141964-04-14,112,BiologistBiologist
5,John SnowJohn Snow,1813-03-151813-03-15,1858-06-161858-06-16,90,PhysicianPhysician
6,Alan TuringAlan Turing,1912-06-231912-06-23,1954-06-071954-06-07,82,Computer ScientistComputer Scientist
7,Johann GaussJohann Gauss,1777-04-301777-04-30,1855-02-231855-02-23,154,MathematicianMathematician

In [201]:
df_sci + df_sci

,Name,Born,Died,Age,Occupation
0,Rosaline FranklinRosaline Franklin,1920-07-251920-07-25,1958-04-161958-04-16,74,ChemistChemist
1,William GossetWilliam Gosset,1876-06-131876-06-13,1937-10-161937-10-16,122,StatisticianStatistician
2,Florence NightingaleFlorence Nightingale,1820-05-121820-05-12,1910-08-131910-08-13,180,NurseNurse
3,Marie CurieMarie Curie,1867-11-071867-11-07,1934-07-041934-07-04,132,ChemistChemist
4,Rachel CarsonRachel Carson,1907-05-271907-05-27,1964-04-141964-04-14,112,BiologistBiologist
5,John SnowJohn Snow,1813-03-151813-03-15,1858-06-161858-06-16,90,PhysicianPhysician
6,Alan TuringAlan Turing,1912-06-231912-06-23,1954-06-071954-06-07,82,Computer ScientistComputer Scientist
7,Johann GaussJohann Gauss,1777-04-301777-04-30,1855-02-231855-02-23,154,MathematicianMathematician

In [204]:
df_sci[df_sci['Age']>df_sci['Age'].mean()] + df_sci['Name']

     0    1    2    3    4    5    6    7  Age Born Died Name Occupation
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        NaN
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        NaN
7  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        NaN

In [205]:
df_sci[df_sci['Age']>df_sci['Age'].mean()]

                   Name        Born        Died  Age     Occupation
1        William Gosset  1876-06-13  1937-10-16   61   Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90          Nurse
3           Marie Curie  1867-11-07  1934-07-04   66        Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77  Mathematician

In [206]:
 df_sci['Name']

0       Rosaline Franklin
1          William Gosset
2    Florence Nightingale
3             Marie Curie
4           Rachel Carson
5               John Snow
6             Alan Turing
7            Johann Gauss
Name: Name, dtype: object

In [213]:
s = pd.Series([0,1,2,3,4,5,6,7,8,9])
s.quantile(0.5)

4.5