https://www.amazon.com/bestsellers
- 如何在竞品检测中使用RFM模型
  - R-Recency   最近一次进入top榜单
  - F-Frequency   进入top榜单次数
  - M-top10    高排名榜单次数/近3天高排名榜单次数

- 针对距离观察日三个月内，将竞品状态分为以下几种类型：重点关注、重点调研、重点保持、一般调研、一般关注、暂不关注；将竞品分为老品，新品两类

| 竞品分类         | 最近一次进入top榜单 | 进入top榜单次数 | **高排名榜单次数** | 近3天高排名榜单次数 | **策略建议**                     |
| ---------------- | ------------------- | --------------- | ------------------ | ------------------- | -------------------------------- |
| **持续关注竞品** | **高**              | **高**          | **高**             | **高**              | **心中有数，最重要竞品**         |
| **重点调研老品** | **高**              | **高**          | **低**             | **高**              | **老品要发力，需运营关注**       |
| **重点调研新品** | **高**              | **低**          | **高**             | **高**              | **需要运营重点研究**             |
| **重点保持老品** | **高**              | **高**          | **高**             | **低**              | **近期排名下降**                 |
| 一般调研新品     | 高/低               | 低              | 低                 | 高                  | 新品期产品，数据监控             |
| 一般调研老品     | 低                  | 高              | 高                 | 低                  | 过了新品期后运营乏力，可数据监控 |
| 一般关注老品     | 高/低               | 高              | 低                 | 低                  | 竞争力相对较弱产品               |
| 暂不关注产品     | 其它情况            |                 |                    |                     |                                  |

### 加载数据

In [1]:
import pandas as pd
df_competitive=pd.read_csv('C:/Develop/深圳42/data/Competitive_product.csv',index_col=[0])
df_competitive.head()

               id  rank  reviews  stars  price     date_d
19665  B073Q6KLGQ     1      634    4.8  59.99  2019/8/26
19666  B01N1U7TE7    51     1448    4.6  59.99  2019/8/26
19667  B01F543PAW     2     2452    4.5  59.99  2019/8/26
19668  B077PVV9RR    52       95    4.4  36.99  2019/8/26
19669  B076KFB49J     3      836    4.7  38.99  2019/8/26

- id 产品id
- rank排名
- reviews 评论数量 
- stars  评星
- price 价格
- date_d

In [2]:
df_competitive.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68859 entries, 19665 to 88523
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       68859 non-null  object
 1   rank     68859 non-null  int64
 2   reviews  68859 non-null  int64
 3   stars    68264 non-null  float64
 4   price    68859 non-null  float64
 5   date_d   68859 non-null  object
dtypes: float64(2), int64(2), object(2)
memory usage: 3.7+ MB

- 基本数据查看

In [3]:
df_competitive.describe()

               rank       reviews         stars          price
count  68859.000000  68859.000000  68264.000000   68859.000000
mean      50.622664    723.181066      4.423768  204441.992416
std       28.901687    809.553512      0.370669  403247.600757
min        1.000000      0.000000      1.000000       4.550000
25%       26.000000    109.000000      4.300000      36.990000
50%       51.000000    375.000000      4.500000      49.990000
75%       76.000000   1068.000000      4.700000      95.000000
max      100.000000   4187.000000      5.000000  999999.000000

In [6]:
df_competitive[df_competitive.price==999999.000000]

               id  rank  reviews  stars     price     date_d
21762  B0769LT7GJ    99      144    3.6  999999.0  2019/8/28
21927  B0769LT7GJ    82      144    3.6  999999.0  2019/8/28
22028  B0769LT7GJ    82      144    3.6  999999.0  2019/8/28
22142  B0769LT7GJ    89      144    3.6  999999.0  2019/8/28
22242  B0769LT7GJ    89      144    3.6  999999.0  2019/8/28
...           ...   ...      ...    ...       ...        ...
88517  B01CQ01YSS    27     4187    4.8  999999.0   2020/3/8
88518  B07TSH3B5J    45       94    4.7  999999.0   2020/3/8
88519  B078PBX7P1    46       57    4.3  999999.0   2020/3/8
88520  B01LYBZ4MJ    47     1746    4.7  999999.0   2020/3/8
88523  B07Z33FG6Y    50       21    4.8  999999.0   2020/3/8

[14075 rows x 6 columns]

In [8]:
df_competitive['id'].nunique()

827

In [9]:
df_competitive['date_d'].value_counts()

2019/8/28     1450
2019/8/30     1300
2019/8/29     1200
2019/8/31     1150
2019/9/1      1100
              ...
2019/11/18     100
2020/3/1       100
2019/11/19     100
2020/2/4       100
2019/12/2      100
Name: date_d, Length: 190, dtype: int64

## 数据清洗

In [10]:
df_competitive.groupby(['id','date_d'])['id'].count()

id          date_d
B000R4KX88  2019/10/11    1
            2019/10/18    1
            2019/10/19    1
            2019/10/20    1
            2019/10/22    1
                         ..
B083W49GJ7  2020/2/24     1
B083W6VN2H  2020/2/23     3
B0842XTXJH  2020/2/29     1
B0849RFGXZ  2020/2/15     1
            2020/2/20     1
Name: id, Length: 24709, dtype: int64

In [12]:
df_competitive[df_competitive['id']=='B000R4KX88']

               id  rank  reviews  stars  price     date_d
20132  B000R4KX88    84      109    2.9    9.8  2019/8/27
20232  B000R4KX88    84      109    2.9    9.8  2019/8/27
21122  B000R4KX88    79      109    2.9    9.8  2019/8/28
21222  B000R4KX88    79      109    2.9    9.8  2019/8/28
21340  B000R4KX88    88      109    2.9    9.8  2019/8/28
...           ...   ...      ...    ...    ...        ...
82007  B000R4KX88    93      122    3.2   10.7  2020/2/14
85101  B000R4KX88    87      122    3.2   10.7  2020/2/27
85353  B000R4KX88    89      133    3.1   10.7  2020/2/28
85585  B000R4KX88    85      133    3.1   10.7  2020/2/29
85858  B000R4KX88    94      133    3.1   10.7  2020/2/29

[76 rows x 6 columns]

- 我们的数据会每天采集多次，所以每天每件商品上榜次数可能不唯一，这里取排名最高的一次

In [15]:
# 
df_competitive_rfm =df_competitive[['id','rank','date_d']].groupby(['id','date_d'],as_index=False).agg({'rank':'min'})
df_competitive_rfm.columns=['id','date_d','rank_min']

In [16]:
# date_d转换为日期时间类型
df_competitive_rfm['date_d'] = pd.to_datetime(df_competitive_rfm['date_d'])

In [17]:
df_competitive_rfm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24709 entries, 0 to 24708
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24709 non-null  object
 1   date_d    24709 non-null  datetime64[ns]
 2   rank_min  24709 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 579.2+ KB

- 判断是否进入Top10，进入Top10作为价值高低的判定依据

In [20]:
# 排行进入前10名记为1 否则是0

df_competitive_rfm['isTop10'] =df_competitive_rfm['rank_min'].apply(lambda x:1 if x<=10 else 0)

- 筛选最近90天的数据来进行RFM打分，数据集中最后的日期是2020年3月8日，我们以这一天为基准

In [24]:
calc_date = df_competitive_rfm['date_d'].max() # 数据集中最后一天作为计算的日期
df_competitive_rfm['date_diff'] =(calc_date - df_competitive_rfm['date_d']).dt.days # 每一天跟计算这一天 算天数差值
df_competitive_rfm_90=df_competitive_rfm[df_competitive_rfm['date_diff']<=90] # 筛选最近90天的数据
df_competitive_rfm_90

               id     date_d  rank_min  isTop10  date_diff
29     B000R4KX88 2020-01-15        63        0         53
30     B000R4KX88 2020-01-23        84        0         45
31     B000R4KX88 2020-01-26        64        0         42
32     B000R4KX88 2020-01-27        92        0         41
33     B000R4KX88 2020-02-14        93        0         23
...           ...        ...       ...      ...        ...
24704  B083W49GJ7 2020-02-24        81        0         13
24705  B083W6VN2H 2020-02-23        41        0         14
24706  B0842XTXJH 2020-02-29        87        0          8
24707  B0849RFGXZ 2020-02-15        78        0         22
24708  B0849RFGXZ 2020-02-20        90        0         17

[11283 rows x 5 columns]

In [27]:
df_competitive_rfm_90.shape
df_competitive_rfm_90.describe()

           rank_min       isTop10     date_diff
count  11283.000000  11283.000000  11283.000000
mean      53.278118      0.085084     43.896304
std       28.419442      0.279019     25.843324
min        1.000000      0.000000      0.000000
25%       29.000000      0.000000     23.000000
50%       55.000000      0.000000     44.000000
75%       78.000000      0.000000     65.000000
max      100.000000      1.000000     90.000000

### 3、计算RFM

- RFM指标计算方法
  - R-Recency 最后一次出现在热销榜距离当前时间的天数
  - F-Frequecy 上榜频次
  - M1-上榜top10的次数
  - M2-近3天进入top10次数
- 计算Recency 最后一次top排名距离现在的时间间隔

In [38]:
r_data = df_competitive_rfm_90.groupby(['id'])[['date_diff']].min()
r_data.columns=['R']
r_data

             R
id
B000R4KX88   8
B00172UV6S  27
B00172UVG8   0
B00172YM40   3
B00172YM9U  13
...         ..
B083V1Q7LH  14
B083W49GJ7  13
B083W6VN2H  14
B0842XTXJH   8
B0849RFGXZ  17

[634 rows x 1 columns]

- 计算F的原始数据（聚合之后的结果），Frequency 有多少次出现在热销榜上

In [37]:
f_data = df_competitive_rfm_90.groupby(['id'])[['rank_min']].count()
f_data.columns=['F']
f_data

             F
id
B000R4KX88   8
B00172UV6S  21
B00172UVG8  87
B00172YM40  47
B00172YM9U  12
...         ..
B083V1Q7LH   1
B083W49GJ7   1
B083W6VN2H   1
B0842XTXJH   1
B0849RFGXZ   2

[634 rows x 1 columns]

In [33]:
df_competitive_rfm_90.columns

Index(['id', 'date_d', 'rank_min', 'isTop10', 'date_diff'], dtype='object')

- M1 上TOP10榜单次数，进入top10 打1，没有进入标记为0, 统计1的次数

In [36]:
m1_data = df_competitive_rfm_90.groupby(['id'])[['isTop10']].sum()
m1_data.columns=['M1']
m1_data

            M1
id
B000R4KX88   0
B00172UV6S   0
B00172UVG8   0
B00172YM40   0
B00172YM9U   0
...         ..
B083V1Q7LH   0
B083W49GJ7   0
B083W6VN2H   0
B0842XTXJH   0
B0849RFGXZ   0

[634 rows x 1 columns]

- M2 近三天上top10次数，体现近期

In [40]:
temp_df = df_competitive_rfm_90[df_competitive_rfm_90['date_diff']<=2]
m2_data = temp_df.groupby(['id'])[['isTop10']].sum()
m2_data.columns=['M2']

- 将RFM的原始数据合并起来

In [41]:
m2_data

            M2
id
B00172UVG8   0
B001LTZZSG   0
B001LU1SFO   1
B001LU39F6   0
B003L7VQMA   0
...         ..
B081VW2GTW   0
B0829TVYYN   0
B0829VD3PN   0
B082X3LZ5R   0
B083JDT7T9   0

[191 rows x 1 columns]

In [44]:
rfm =pd.concat([r_data,f_data,m1_data,m2_data],axis=1)
rfm.fillna(0,inplace=True)
rfm.describe()

                R           F          M1          M2
count  634.000000  634.000000  634.000000  634.000000
mean    21.198738   17.796530    1.514196    0.059937
std     22.624099   25.105614    9.992127    0.392912
min      0.000000    1.000000    0.000000    0.000000
25%      2.000000    2.000000    0.000000    0.000000
50%     13.000000    6.000000    0.000000    0.000000
75%     36.000000   21.000000    0.000000    0.000000
max     90.000000   88.000000   86.000000    3.000000

### 4、 RFM打分

| 按照运营需求打分 | 最近一次上榜-R | 上榜次数-F | 进入top10榜单次数-M1 | 近3天进入top10次数-M2 |
| ---------------- | -------------- | ---------- | -------------------- | --------------------- |
| 1                | 80天以上       | 小于20次   | 小于5次              | 1次                   |
| 2                | 30-80天        | 20-40次    | 5-20次               | 2次                   |
| 3                | 15-30天        | 40-60次    | 20-60次              | 3次                   |
| 4                | 3-15天         | 60-80次    | 60-80次              |                       |
| 5                | 3天以内        | 80次以上   | 80次以上             |                       |

- 通过pd.cut方法，将用户分层并打上标签， 打分规则见上面表格

In [45]:
rfm.shape[0]

634

In [60]:
r_bins = [0,3,15,30,80,999]
labels = [i for i in range(len(r_bins)-1,0,-1)]
rfm['R_score'] = pd.cut(rfm['R'],bins=r_bins,labels=labels,include_lowest=True).astype(int)
f_bins = [0,20,40,60,80,999]
labels = [i for i in range(1,len(f_bins))]
rfm['F_score'] = pd.cut(rfm['F'],bins=f_bins,labels=labels,include_lowest=True).astype(int)
m1_bins = [0,5,20,60,80,999]
labels = [i for i in range(1,len(m1_bins))]
rfm['M1_score'] = pd.cut(rfm['M1'],bins=m1_bins,labels=labels,include_lowest=True).astype(int)
m2_bins = [0,1,2,3,100]
labels = [i for i in range(1,len(m2_bins))]
rfm['M2_score'] = pd.cut(rfm['M2'],bins=m2_bins,labels=labels,include_lowest=True).astype(int)

In [58]:
rfm['rfm_labels']

             R   F  M1   M2 R_score F_score M1_score M2_score
id
B000R4KX88   8   8   0  0.0       4       1        1        1
B00172UV6S  27  21   0  0.0       3       2        1        1
B00172UVG8   0  87   0  0.0       5       5        1        1
B00172YM40   3  47   0  0.0       5       3        1        1
B00172YM9U  13  12   0  0.0       4       1        1        1
...         ..  ..  ..  ...     ...     ...      ...      ...
B083V1Q7LH  14   1   0  0.0       4       1        1        1
B083W49GJ7  13   1   0  0.0       4       1        1        1
B083W6VN2H  14   1   0  0.0       4       1        1        1
B0842XTXJH   8   1   0  0.0       4       1        1        1
B0849RFGXZ  17   2   0  0.0       3       1        1        1

[634 rows x 8 columns]

In [55]:
[i for i in range(1,len(f_bins))]

[1, 2, 3, 4, 5]

- 然后我们对不同指标1~5分计算平均值，高于/低于平均值的，进一步二分 每个维度均标记为高或低

In [62]:
rfm['R_label'] = rfm['R_score'].apply(lambda x:'高' if x>rfm['R_score'].mean() else '低')
rfm['F_label'] = rfm['F_score'].apply(lambda x:'高' if x>rfm['F_score'].mean() else '低')
rfm['M1_label'] = rfm['M1_score'].apply(lambda x:'高' if x>rfm['M1_score'].mean() else '低')
rfm['M2_label'] = rfm['M2_score'].apply(lambda x:'高' if x>rfm['M2_score'].mean() else '低')

In [64]:
rfm['rfm_label'] = rfm['R_label']+rfm['F_label']+rfm['M1_label']+rfm['M2_label']

- 将不同的类别，打上不同的标签，不同的标签，就是不同的产品类型，也就是不同的对待策略

In [65]:
# 分层规则
rfm2cat={
    '高高高高':'持续关注竞品',
    '高高低高':'重点调研老品',
    '高低高高':'重点调研新品',
    '高高高低':'重点保持老品',
    '低低低高':'一般调研新品',
    '高低低高':'一般调研新品',
    '低高高低':'一半调研老品',
    '高高低低':'一般关注老品',
    '低高低低':'一般关注老品',
}

In [ ]:
# 按照标签分类，查看每类商品的数量， 如果有没打上标签的， 用暂不关注产品 填充

In [67]:
rfm['product_label'] = rfm['rfm_label'].map(rfm2cat)

In [68]:
rfm['product_label'].fillna('暂不关注产品',inplace=True)

In [70]:
rfm['product_label'].value_counts()

暂不关注产品    469
一般关注老品    146
持续关注竞品     11
重点保持老品      6
重点调研老品      1
一般调研新品      1
Name: product_label, dtype: int64