In [1]:
import pandas as pd
df1 = pd.DataFrame([[1, 2, 3], [1, 10, 20], [5, 6,7], [3, 9, 0], [8, 0, 3]], columns=['x1', 'x2', 'x3'])
df2 = pd.DataFrame([[1, 2], [1, 10], [1, 3], [4, 6], [3, 9]], columns=['x1', 'x4'])
print(df1)
print(df2)

   x1  x2  x3
0   1   2   3
1   1  10  20
2   5   6   7
3   3   9   0
4   8   0   3
   x1  x4
0   1   2
1   1  10
2   1   3
3   4   6
4   3   9

## df.append() 了解

In [3]:
df1.append(df2) # df1后面追加一些新的行, df1和df2的数据, 如果列名相同就能够追加到一起, 如果列名不同, 拼接不上的部分用NaN填充

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3224\2995832154.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)

   x1    x2    x3    x4
0   1   2.0   3.0   NaN
1   1  10.0  20.0   NaN
2   5   6.0   7.0   NaN
3   3   9.0   0.0   NaN
4   8   0.0   3.0   NaN
0   1   NaN   NaN   2.0
1   1   NaN   NaN  10.0
2   1   NaN   NaN   3.0
3   4   NaN   NaN   6.0
4   3   NaN   NaN   9.0

In [4]:
df1.append(df2, ignore_index=True) # ignore_index 拼接之后, 忽略索引 索引会从0开始一路数下去  默认会保留之前的索引

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3224\1954622792.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2, ignore_index=True)

   x1    x2    x3    x4
0   1   2.0   3.0   NaN
1   1  10.0  20.0   NaN
2   5   6.0   7.0   NaN
3   3   9.0   0.0   NaN
4   8   0.0   3.0   NaN
5   1   NaN   NaN   2.0
6   1   NaN   NaN  10.0
7   1   NaN   NaN   3.0
8   4   NaN   NaN   6.0
9   3   NaN   NaN   9.0

## pd.concat  需要掌握

In [5]:
pd.concat([df1, df2], ignore_index=True)

   x1    x2    x3    x4
0   1   2.0   3.0   NaN
1   1  10.0  20.0   NaN
2   5   6.0   7.0   NaN
3   3   9.0   0.0   NaN
4   8   0.0   3.0   NaN
5   1   NaN   NaN   2.0
6   1   NaN   NaN  10.0
7   1   NaN   NaN   3.0
8   4   NaN   NaN   6.0
9   3   NaN   NaN   9.0

In [6]:
pd.concat([df1, df2], axis=1)

   x1  x2  x3  x1  x4
0   1   2   3   1   2
1   1  10  20   1  10
2   5   6   7   1   3
3   3   9   0   4   6
4   8   0   3   3   9

In [9]:
pd.concat([df1.set_index(['x1']), df2], axis=1)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [10]:
df3 = pd.DataFrame([[1, 2], [1, 10], [1, 3], [4, 6], [3, 9]], columns=['x1', 'x4'],index=['a', 'b', 'c', 'd', 'e'])

In [14]:
pd.concat([df1, df3], axis=0, join='outer')

   x1    x2    x3    x4
0   1   2.0   3.0   NaN
1   1  10.0  20.0   NaN
2   5   6.0   7.0   NaN
3   3   9.0   0.0   NaN
4   8   0.0   3.0   NaN
a   1   NaN   NaN   2.0
b   1   NaN   NaN  10.0
c   1   NaN   NaN   3.0
d   4   NaN   NaN   6.0
e   3   NaN   NaN   9.0

## merge连接 和SQL的join基本相同, 需要掌握

In [15]:
df1

   x1  x2  x3
0   1   2   3
1   1  10  20
2   5   6   7
3   3   9   0
4   8   0   3

In [16]:
df2

   x1  x4
0   1   2
1   1  10
2   1   3
3   4   6
4   3   9

In [17]:
df1.merge(df2,on='x1',how='left')

   x1  x2  x3    x4
0   1   2   3   2.0
1   1   2   3  10.0
2   1   2   3   3.0
3   1  10  20   2.0
4   1  10  20  10.0
5   1  10  20   3.0
6   5   6   7   NaN
7   3   9   0   9.0
8   8   0   3   NaN

In [18]:
df1.merge(df2,on='x1',how='right')

   x1    x2    x3  x4
0   1   2.0   3.0   2
1   1  10.0  20.0   2
2   1   2.0   3.0  10
3   1  10.0  20.0  10
4   1   2.0   3.0   3
5   1  10.0  20.0   3
6   4   NaN   NaN   6
7   3   9.0   0.0   9

In [19]:
df1.merge(df2,on='x1',how='inner')

   x1  x2  x3  x4
0   1   2   3   2
1   1   2   3  10
2   1   2   3   3
3   1  10  20   2
4   1  10  20  10
5   1  10  20   3
6   3   9   0   9

In [20]:
df1.merge(df2,on='x1',how='outer')

   x1    x2    x3    x4
0   1   2.0   3.0   2.0
1   1   2.0   3.0  10.0
2   1   2.0   3.0   3.0
3   1  10.0  20.0   2.0
4   1  10.0  20.0  10.0
5   1  10.0  20.0   3.0
6   5   6.0   7.0   NaN
7   3   9.0   0.0   9.0
8   8   0.0   3.0   NaN
9   4   NaN   NaN   6.0

In [22]:
df1.merge(df2,left_on='x3',right_on='x1',how='left',suffixes=['_left','_right'])
# 如果要关联的两张表使用的列名不一样, 通过left_on 和 right_on 来指定
#  left_on 左表出哪一列用于关联
#  right_on  右表出哪一列用于关联
#  suffixes=['_left','_right']  两张表关联之后, 如果有相同的列名, 通过这个参数可以指定后缀 默认是['_x','_y']

   x1_left  x2  x3  x1_right   x4
0        1   2   3       3.0  9.0
1        1  10  20       NaN  NaN
2        5   6   7       NaN  NaN
3        3   9   0       NaN  NaN
4        8   0   3       3.0  9.0

In [ ]:
## join拼接 
# concat 和 merge  的功能稍微调整就可以实现join的效果

In [27]:
df1.join(df3,rsuffix='_right',lsuffix='_left',how='outer')

   x1_left    x2    x3  x1_right    x4
0      1.0   2.0   3.0       NaN   NaN
1      1.0  10.0  20.0       NaN   NaN
2      5.0   6.0   7.0       NaN   NaN
3      3.0   9.0   0.0       NaN   NaN
4      8.0   0.0   3.0       NaN   NaN
a      NaN   NaN   NaN       1.0   2.0
b      NaN   NaN   NaN       1.0  10.0
c      NaN   NaN   NaN       1.0   3.0
d      NaN   NaN   NaN       4.0   6.0
e      NaN   NaN   NaN       3.0   9.0

In [25]:
pd.concat([df1,df2],axis=1)

   x1  x2  x3  x1  x4
0   1   2   3   1   2
1   1  10  20   1  10
2   5   6   7   1   3
3   3   9   0   4   6
4   8   0   3   3   9

In [32]:
df1.join(df2,on='x1' ,rsuffix='_right',lsuffix='_left')

   x1_left  x2  x3  x1_right    x4
0        1   2   3       1.0  10.0
1        1  10  20       1.0  10.0
2        5   6   7       NaN   NaN
3        3   9   0       4.0   6.0
4        8   0   3       NaN   NaN

In [28]:
df1

   x1  x2  x3
0   1   2   3
1   1  10  20
2   5   6   7
3   3   9   0
4   8   0   3

In [29]:
df2

   x1  x4
0   1   2
1   1  10
2   1   3
3   4   6
4   3   9

## 转置

In [33]:
df1.T

    0   1  2  3  4
x1  1   1  5  3  8
x2  2  10  6  9  0
x3  3  20  7  0  3

## 数据透视表

In [35]:
uniqlo_df = pd.read_csv('C:/Develop/深圳42/data/uniqlo.csv')
uniqlo_df.head()

   店铺id  城市 销售渠道      性别    年龄段     消费时间  产品名称  客户数量   销售金额  订单数量  产品数量  单件成本
0   658  深圳   线下  Female  25-29  Weekday  当季新品     4  796.0     4     4    59
1   146  杭州   线下  Female  25-29  Weekday    运动     1  149.0     1     1    49
2    70  深圳   线下    Male   >=60  Weekday    T恤     2  178.0     2     2    49
3   658  深圳   线下  Female  25-29  Weekday    T恤     1   59.0     1     1    49
4   229  深圳   线下    Male  20-24  Weekend    袜子     2   65.0     2     3     9

In [36]:
uniqlo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22293 entries, 0 to 22292
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   店铺id    22293 non-null  int64
 1   城市      22293 non-null  object
 2   销售渠道    22293 non-null  object
 3   性别      22293 non-null  object
 4   年龄段     22293 non-null  object
 5   消费时间    22293 non-null  object
 6   产品名称    22293 non-null  object
 7   客户数量    22293 non-null  int64
 8   销售金额    22293 non-null  float64
 9   订单数量    22293 non-null  int64
 10  产品数量    22293 non-null  int64
 11  单件成本    22293 non-null  int64
dtypes: float64(1), int64(5), object(6)
memory usage: 2.0+ MB

In [37]:
uniqlo_df.describe()

,店铺id,客户数量,销售金额,订单数量,产品数量,单件成本
count,22293.000000,22293.000000,22293.000000,22293.000000,22293.000000,22293.000000
mean,335.391558,1.629480,159.531371,1.651998,1.858072,46.124658
std,230.236167,1.785605,276.254066,1.861480,2.347301,19.124347
min,19.000000,1.000000,-0.660000,1.000000,1.000000,9.000000
25%,142.000000,1.000000,64.000000,1.000000,1.000000,49.000000
50%,315.000000,1.000000,99.000000,1.000000,1.000000,49.000000
75%,480.000000,2.000000,175.000000,2.000000,2.000000,49.000000
max,831.000000,58.000000,12538.000000,65.000000,84.000000,99.000000

In [39]:
# 每个城市线下门店各种品类商品总销售额
uniqlo_df_offline = uniqlo_df[uniqlo_df['销售渠道']=='线下']

In [42]:
uniqlo_df_offline.groupby(['城市','产品名称'])['销售金额'].sum().reset_index()

    城市  产品名称       销售金额
0   上海    T恤  126778.56
1   上海  当季新品   39138.31
2   上海    毛衣   18766.67
3   上海   牛仔裤   22752.47
4   上海    短裤    7206.38
..  ..   ...        ...
85  重庆    短裤    6149.23
86  重庆    袜子    8024.23
87  重庆    裙子    7897.00
88  重庆    运动    9284.50
89  重庆    配件   30133.90

[90 rows x 3 columns]

In [40]:
uniqlo_df_offline.columns

Index(['店铺id', '城市', '销售渠道', '性别', '年龄段', '消费时间', '产品名称', '客户数量', '销售金额',
       '订单数量', '产品数量', '单件成本'],
      dtype='object')

In [43]:
uniqlo_df_offline.pivot_table(index='城市',columns='产品名称',values='销售金额',aggfunc='sum')

产品名称,T恤,当季新品,毛衣,牛仔裤,短裤,袜子,裙子,运动,配件
城市,,,,,,,,,
上海,126778.56,39138.31,18766.67,22752.47,7206.38,9336.49,9632.93,9119.17,32652.66
北京,70349.96,18854.86,7210.68,4309.00,3241.67,4658.24,3829.55,2214.00,15790.66
南京,47702.91,36697.68,7525.10,5753.63,1836.22,4258.62,4168.00,1406.34,13802.43
广州,47157.01,18994.00,10461.00,6169.00,3481.07,4724.00,8013.56,3929.32,14302.23
成都,89127.68,35935.63,15638.33,14922.04,7103.22,8095.41,10160.33,7678.66,19528.56
杭州,253602.43,99377.30,45169.62,36259.89,17715.38,21559.65,21385.04,23875.08,70574.10
武汉,132910.00,64175.42,15849.00,27968.16,8709.19,9866.31,13669.26,11760.96,23448.75
深圳,309042.79,127637.43,44161.03,50120.39,23214.33,25822.56,27572.11,24339.68,101213.36
西安,83574.01,24108.42,17331.74,12822.32,5341.88,4967.47,7086.00,5629.27,19825.50
重庆,96568.24,41494.58,16784.00,20826.62,6149.23,8024.23,7897.00,9284.50,30133.90

In [45]:
uniqlo_df_offline.pivot_table(index=['城市','消费时间'],columns=['产品名称'],values='销售金额',aggfunc='sum')

产品名称               T恤      当季新品        毛衣       牛仔裤        短裤        袜子  \
城市 消费时间
上海 Weekday   75351.56  21631.31   9212.67  11379.47   4269.38   5549.49
   Weekend   51427.00  17507.00   9554.00  11373.00   2937.00   3787.00
北京 Weekday   40663.68  10929.86   5318.68   1671.00   1945.67   3104.24
   Weekend   29686.28   7925.00   1892.00   2638.00   1296.00   1554.00
南京 Weekday   27130.33  31709.93   3671.84   2283.63   1244.22   2291.62
   Weekend   20572.58   4987.75   3853.26   3470.00    592.00   1967.00
广州 Weekday   24685.46  12301.00   6336.00   3704.00   2039.07   3176.00
   Weekend   22471.55   6693.00   4125.00   2465.00   1442.00   1548.00
成都 Weekday   56320.05  20958.15   9702.33   9763.04   3571.22   4964.41
   Weekend   32807.63  14977.48   5936.00   5159.00   3532.00   3131.00
杭州 Weekday  149695.09  58455.30  26874.62  23040.39  10491.38  12110.39
   Weekend  103907.34  40922.00  18295.00  13219.50   7224.00   9449.26
武汉 Weekday   81854.39  29346.17  10877.00  20742.24   4550.19   5453.31
   Weekend   51055.61  34829.25   4972.00   7225.92   4159.00   4413.00
深圳 Weekday  178778.29  74611.13  25582.03  24454.08  12545.33  15440.66
   Weekend  130264.50  53026.30  18579.00  25666.31  10669.00  10381.90
西安 Weekday   46578.06  10162.88   7704.74   8477.32   2913.88   3246.47
   Weekend   36995.95  13945.54   9627.00   4345.00   2428.00   1721.00
重庆 Weekday   53153.31  26150.32   6825.00  12637.62   2801.23   5000.23
   Weekend   43414.93  15344.26   9959.00   8189.00   3348.00   3024.00

产品名称              裙子        运动        配件
城市 消费时间
上海 Weekday   5337.93   4613.17  16423.89
   Weekend   4295.00   4506.00  16228.77
北京 Weekday   3432.55   1334.00   7111.66
   Weekend    397.00    880.00   8679.00
南京 Weekday   2030.00    830.34   9590.15
   Weekend   2138.00    576.00   4212.28
广州 Weekday   4917.56   2622.32   8934.23
   Weekend   3096.00   1307.00   5368.00
成都 Weekday   4870.33   4664.66  11631.56
   Weekend   5290.00   3014.00   7897.00
杭州 Weekday  12683.04  14329.64  45896.13
   Weekend   8702.00   9545.44  24677.97
武汉 Weekday   7735.26   7431.64  12919.04
   Weekend   5934.00   4329.32  10529.71
深圳 Weekday  14624.11  15950.24  64149.56
   Weekend  12948.00   8389.44  37063.80
西安 Weekday   5020.00   2191.27  12050.50
   Weekend   2066.00   3438.00   7775.00
重庆 Weekday   3861.00   5618.51  18409.43
   Weekend   4036.00   3665.99  11724.47

In [46]:
uniqlo_df.pivot_table(index=['城市','销售渠道'],columns=['产品名称'],values='销售金额',aggfunc='sum')

产品名称            T恤       当季新品        毛衣       牛仔裤        短裤        袜子  \
城市 销售渠道
上海 线上     48637.48   16136.50   5019.00   9264.93   4453.04   4379.45
   线下    126778.56   39138.31  18766.67  22752.47   7206.38   9336.49
北京 线下     70349.96   18854.86   7210.68   4309.00   3241.67   4658.24
南京 线下     47702.91   36697.68   7525.10   5753.63   1836.22   4258.62
广州 线上     93729.71   26574.95  14410.00   9957.90   6433.92   8791.61
   线下     47157.01   18994.00  10461.00   6169.00   3481.07   4724.00
成都 线下     89127.68   35935.63  15638.33  14922.04   7103.22   8095.41
杭州 线下    253602.43   99377.30  45169.62  36259.89  17715.38  21559.65
武汉 线上    120358.13   32243.46  22981.63  19537.13   9894.47  10715.32
   线下    132910.00   64175.42  15849.00  27968.16   8709.19   9866.31
深圳 线下    309042.79  127637.43  44161.03  50120.39  23214.33  25822.56
西安 线上     11311.93    4158.34   1095.00   3043.00   1127.00   1458.00
   线下     83574.01   24108.42  17331.74  12822.32   5341.88   4967.47
重庆 线上      7894.00    5138.00   3228.00   2421.00   1578.88   1074.00
   线下     96568.24   41494.58  16784.00  20826.62   6149.23   8024.23

产品名称           裙子        运动         配件
城市 销售渠道
上海 线上     5341.00   2264.00   18942.69
   线下     9632.93   9119.17   32652.66
北京 线下     3829.55   2214.00   15790.66
南京 线下     4168.00   1406.34   13802.43
广州 线上     5932.00   6438.67   28624.54
   线下     8013.56   3929.32   14302.23
成都 线下    10160.33   7678.66   19528.56
杭州 线下    21385.04  23875.08   70574.10
武汉 线上    10086.00   6106.36   49498.23
   线下    13669.26  11760.96   23448.75
深圳 线下    27572.11  24339.68  101213.36
西安 线上     2331.00   1386.20    4177.54
   线下     7086.00   5629.27   19825.50
重庆 线上      199.00   2627.47    2170.00
   线下     7897.00   9284.50   30133.90