In [1]:
import pandas as pd
df = pd.read_csv('C:/Develop/深圳42/data/LJdata.csv')

In [2]:
df.nlargest(5,'价格') # largest 最大的前n个

         区域       地址    户型   面积      价格     朝向        更新时间  看房人数
2658  和平里租房   雍和家园二期  6室3厅  720  210000      南  2017.07.26    21
2010  酒仙桥租房     阳光上东  4室2厅  285   45000    南 北  2017.07.26     6
2050   官园租房   西派国际公寓  3室2厅  191   40000  东 南 西  2017.07.20    25
662   东直门租房  万国城MOMA  3室2厅  244   36500     东南  2017.07.17    15
2012  太阳宫租房     太阳公元  3室2厅  159   36000    南 北  2017.07.27    15

In [3]:
df.nsmallest(5,'看房人数') # smallest 最小的n个

        区域         地址    户型   面积     价格     朝向        更新时间  看房人数
184   望京租房    大西洋新城A区  3室2厅  162  18000  东南 西北  2017.07.24     0
188   常营租房  万象新天天际高尔夫  3室2厅  172  11500    南 北  2017.07.24     0
192   望京租房    大西洋新城G区  3室2厅  141  24000    东 西  2017.07.25     0
347   劲松租房       武圣西里  3室1厅   73   6500   东南 北  2017.07.27     0
575  东直门租房    胡家园26号院  3室2厅  132  14000    南 北  2017.07.24     0

In [8]:
df.sort_values(['价格','面积'],ascending=[False,True])
# 多字段排序, by可以通过列表,传入多个字段,   ascending 也可以传入列表 分别指定每个字段的升序/降序的情况 升序降序列表长度需要和排序字段长度一致

         区域       地址    户型   面积      价格     朝向        更新时间  看房人数
2658  和平里租房   雍和家园二期  6室3厅  720  210000      南  2017.07.26    21
2010  酒仙桥租房     阳光上东  4室2厅  285   45000    南 北  2017.07.26     6
2050   官园租房   西派国际公寓  3室2厅  191   40000  东 南 西  2017.07.20    25
662   东直门租房  万国城MOMA  3室2厅  244   36500     东南  2017.07.17    15
2012  太阳宫租房     太阳公元  3室2厅  159   36000    南 北  2017.07.27    15
...     ...      ...   ...  ...     ...    ...         ...   ...
2610   南口租房     南厂北区  2室1厅   58    1800    南 北  2017.07.22     0
1614   良乡租房   北关东路社区  1室1厅   36    1700      南  2017.07.23     5
591    北关租房    西潞苑小区  2室1厅   78    1500      西  2017.07.26     1
629    北关租房    西潞苑小区  2室1厅   78    1500      西  2017.07.26     1
2527   良乡租房   伟业嘉园西里  1室1厅   46    1300      南  2017.07.19    14

[2760 rows x 8 columns]

In [10]:
df.corr(numeric_only=True)
#  相关系数  判断两列数据是否同增同减   [-1,1]
#  如果一个变量增大的时候, 另一个变量也跟一起增大 正相关  最大 1
#  如果一个变量增大的时候, 另一个变量减小 负相关         最小 -1
#  相关系数的绝对值 >0.7 强相关  0.3~0.7 具有相关性   0.3以下 弱相关  0附近 不相关

            面积        价格      看房人数
面积    1.000000  0.710056 -0.114706
价格    0.710056  1.000000  0.019457
看房人数 -0.114706  0.019457  1.000000

In [13]:
df[df['区域']=='望京租房'].corr()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_20816\1776054070.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[df['区域']=='望京租房'].corr()

            面积        价格      看房人数
面积    1.000000  0.873137 -0.025644
价格    0.873137  1.000000 -0.116956
看房人数 -0.025644 -0.116956  1.000000

In [ ]:
# 相关不等于因果, 但是找因果关系 相关性是很重要的指标