In [1]:
from numpy import NaN,NAN,nan
print(NaN==True)
print(NaN==False)
print(NaN==0)
print(NaN=='')
print(NaN==None)

False
False
False
False
False

In [2]:
print(NaN==NaN)
print(NaN==nan)
print(NaN==NAN)
print(nan==NAN)

False
False
False
False

In [3]:
type(NaN)

float

In [5]:
import pandas as pd
df = pd.read_csv('C:/Develop/深圳42/data/city_day.csv')

In [10]:
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

In [8]:
df.describe()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
count,24933.000000,18391.000000,25949.000000,25946.000000,25346.000000,19203.000000,27472.000000,25677.000000,25509.000000,23908.000000,21490.000000,11422.000000,24850.000000
mean,67.450578,118.127103,17.574730,28.560659,32.309123,23.483476,2.248598,14.531977,34.491430,3.280840,8.700972,3.070128,166.463581
std,64.661449,90.605110,22.785846,24.474746,31.646011,25.684275,6.962884,18.133775,21.694928,15.811136,19.969164,6.323247,140.696585
min,0.040000,0.010000,0.020000,0.010000,0.000000,0.010000,0.000000,0.010000,0.010000,0.000000,0.000000,0.000000,13.000000
25%,28.820000,56.255000,5.630000,11.750000,12.820000,8.580000,0.510000,5.670000,18.860000,0.120000,0.600000,0.140000,81.000000
50%,48.570000,95.680000,9.890000,21.690000,23.520000,15.850000,0.890000,9.160000,30.840000,1.070000,2.970000,0.980000,118.000000
75%,80.590000,149.745000,19.950000,37.620000,40.127500,30.020000,1.450000,15.220000,45.570000,3.080000,9.150000,3.350000,208.000000
max,949.990000,1000.000000,390.680000,362.210000,467.630000,352.890000,175.810000,193.860000,257.730000,455.030000,454.850000,170.370000,2049.000000

In [12]:
df = pd.read_csv('C:/Develop/深圳42/data/city_day.csv',keep_default_na=False)
# 是否用默认的方式来加载空值, 默认加载成NaN 改成False 就会加载成空串
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,,,0.92,18.22,17.15,,0.92,27.64,133.36,0.0,0.02,0.0,,
1,Ahmedabad,2015-01-02,,,0.97,15.69,16.46,,0.97,24.55,34.06,3.68,5.5,3.77,,
2,Ahmedabad,2015-01-03,,,17.4,19.3,29.7,,17.4,29.07,30.7,6.8,16.4,2.25,,
3,Ahmedabad,2015-01-04,,,1.7,18.48,17.97,,1.7,18.59,36.08,4.43,10.14,1.0,,
4,Ahmedabad,2015-01-05,,,22.1,21.42,37.76,,22.1,39.33,39.31,7.01,18.89,2.78,,

In [13]:
df.loc[0,'PM2.5']

''

In [14]:
pd.read_csv('C:/Develop/深圳42/data/city_day.csv',na_values='0.0')
# na_values 可以指定某些特殊的值, 在加载数据的时候当作空值来对待

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,NaN,0.02,NaN,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,19.54,12.47,0.47,8.55,23.30,2.24,12.07,0.73,41.0,Good
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,16.53,11.99,0.52,12.72,30.14,0.74,2.21,0.38,70.0,Satisfactory
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,18.33,10.71,0.48,8.42,30.96,0.01,0.01,NaN,68.0,Satisfactory
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,18.80,10.03,0.52,9.84,28.30,NaN,NaN,NaN,54.0,Satisfactory
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,NaN,NaN,NaN,50.0,Good

## 缺失值的判断

In [17]:
df = pd.read_csv('C:/Develop/深圳42/data/city_day.csv')
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [26]:
df.isnull().sum()

City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

## 缺失值删除

In [28]:
df2 = df.sample(10,random_state=5)
df2

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
17374,Jaipur,2019-08-10,16.14,35.13,6.77,8.97,13.40,24.65,0.51,10.69,24.24,0.15,2.41,NaN,48.0,Good
2117,Aizawl,2020-06-27,0.16,3.16,11.69,0.07,15.41,22.42,0.02,1.08,1.29,NaN,NaN,NaN,19.0,Good
18360,Jorapokhar,2019-02-08,120.88,211.96,9.60,10.56,NaN,6.28,NaN,130.00,16.21,NaN,NaN,NaN,289.0,Poor
24153,Patna,2016-03-16,104.17,NaN,12.81,19.89,22.09,NaN,1.17,6.99,29.60,0.15,0.62,0.25,241.0,Poor
22815,Mumbai,2017-08-18,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,0.00,0.00,0.00,NaN,NaN
1474,Ahmedabad,2019-01-14,75.49,NaN,9.04,61.80,19.74,NaN,9.04,34.03,80.26,4.16,32.44,7.03,407.0,Severe
21380,Lucknow,2019-03-15,77.39,NaN,5.23,38.80,27.92,12.61,1.00,9.74,39.39,1.33,19.15,NaN,212.0,Poor
29365,Visakhapatnam,2020-01-18,42.17,81.73,4.40,25.01,16.89,10.84,1.03,8.03,45.73,3.42,4.56,0.86,79.0,Satisfactory
25299,Patna,2019-05-06,72.28,NaN,8.76,13.55,8.82,NaN,1.11,44.82,86.50,1.60,15.17,5.99,186.0,Moderate
17691,Jaipur,2020-06-22,34.32,67.36,5.51,16.12,18.65,25.60,0.68,10.04,53.53,0.47,0.79,NaN,80.0,Satisfactory

In [29]:
df2.dropna()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
29365,Visakhapatnam,2020-01-18,42.17,81.73,4.4,25.01,16.89,10.84,1.03,8.03,45.73,3.42,4.56,0.86,79.0,Satisfactory

In [30]:
df2.isnull().sum(1)

17374     1
2117      3
18360     5
24153     2
22815    10
1474      2
21380     2
29365     0
25299     2
17691     1
dtype: int64

In [34]:
df2.dropna(subset=['PM2.5','CO'])

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
17374,Jaipur,2019-08-10,16.14,35.13,6.77,8.97,13.40,24.65,0.51,10.69,24.24,0.15,2.41,NaN,48.0,Good
2117,Aizawl,2020-06-27,0.16,3.16,11.69,0.07,15.41,22.42,0.02,1.08,1.29,NaN,NaN,NaN,19.0,Good
24153,Patna,2016-03-16,104.17,NaN,12.81,19.89,22.09,NaN,1.17,6.99,29.60,0.15,0.62,0.25,241.0,Poor
1474,Ahmedabad,2019-01-14,75.49,NaN,9.04,61.80,19.74,NaN,9.04,34.03,80.26,4.16,32.44,7.03,407.0,Severe
21380,Lucknow,2019-03-15,77.39,NaN,5.23,38.80,27.92,12.61,1.00,9.74,39.39,1.33,19.15,NaN,212.0,Poor
29365,Visakhapatnam,2020-01-18,42.17,81.73,4.40,25.01,16.89,10.84,1.03,8.03,45.73,3.42,4.56,0.86,79.0,Satisfactory
25299,Patna,2019-05-06,72.28,NaN,8.76,13.55,8.82,NaN,1.11,44.82,86.50,1.60,15.17,5.99,186.0,Moderate
17691,Jaipur,2020-06-22,34.32,67.36,5.51,16.12,18.65,25.60,0.68,10.04,53.53,0.47,0.79,NaN,80.0,Satisfactory

In [37]:
df2.dropna(thresh=12)
# 设置阈值, 设置了每一行/列 非空元素的下限, 当每一行/列 非空值小于这个阈值时就会被删除

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
17374,Jaipur,2019-08-10,16.14,35.13,6.77,8.97,13.40,24.65,0.51,10.69,24.24,0.15,2.41,NaN,48.0,Good
2117,Aizawl,2020-06-27,0.16,3.16,11.69,0.07,15.41,22.42,0.02,1.08,1.29,NaN,NaN,NaN,19.0,Good
24153,Patna,2016-03-16,104.17,NaN,12.81,19.89,22.09,NaN,1.17,6.99,29.60,0.15,0.62,0.25,241.0,Poor
1474,Ahmedabad,2019-01-14,75.49,NaN,9.04,61.80,19.74,NaN,9.04,34.03,80.26,4.16,32.44,7.03,407.0,Severe
21380,Lucknow,2019-03-15,77.39,NaN,5.23,38.80,27.92,12.61,1.00,9.74,39.39,1.33,19.15,NaN,212.0,Poor
29365,Visakhapatnam,2020-01-18,42.17,81.73,4.40,25.01,16.89,10.84,1.03,8.03,45.73,3.42,4.56,0.86,79.0,Satisfactory
25299,Patna,2019-05-06,72.28,NaN,8.76,13.55,8.82,NaN,1.11,44.82,86.50,1.60,15.17,5.99,186.0,Moderate
17691,Jaipur,2020-06-22,34.32,67.36,5.51,16.12,18.65,25.60,0.68,10.04,53.53,0.47,0.79,NaN,80.0,Satisfactory

In [41]:
df2.dropna(subset=['PM2.5','PM10'],how='all')

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
17374,Jaipur,2019-08-10,16.14,35.13,6.77,8.97,13.40,24.65,0.51,10.69,24.24,0.15,2.41,NaN,48.0,Good
2117,Aizawl,2020-06-27,0.16,3.16,11.69,0.07,15.41,22.42,0.02,1.08,1.29,NaN,NaN,NaN,19.0,Good
18360,Jorapokhar,2019-02-08,120.88,211.96,9.60,10.56,NaN,6.28,NaN,130.00,16.21,NaN,NaN,NaN,289.0,Poor
24153,Patna,2016-03-16,104.17,NaN,12.81,19.89,22.09,NaN,1.17,6.99,29.60,0.15,0.62,0.25,241.0,Poor
1474,Ahmedabad,2019-01-14,75.49,NaN,9.04,61.80,19.74,NaN,9.04,34.03,80.26,4.16,32.44,7.03,407.0,Severe
21380,Lucknow,2019-03-15,77.39,NaN,5.23,38.80,27.92,12.61,1.00,9.74,39.39,1.33,19.15,NaN,212.0,Poor
29365,Visakhapatnam,2020-01-18,42.17,81.73,4.40,25.01,16.89,10.84,1.03,8.03,45.73,3.42,4.56,0.86,79.0,Satisfactory
25299,Patna,2019-05-06,72.28,NaN,8.76,13.55,8.82,NaN,1.11,44.82,86.50,1.60,15.17,5.99,186.0,Moderate
17691,Jaipur,2020-06-22,34.32,67.36,5.51,16.12,18.65,25.60,0.68,10.04,53.53,0.47,0.79,NaN,80.0,Satisfactory

In [44]:
df2['PM2.5']

17374     16.14
2117       0.16
18360    120.88
24153    104.17
22815       NaN
1474      75.49
21380     77.39
29365     42.17
25299     72.28
17691     34.32
Name: PM2.5, dtype: float64

In [43]:
df2['PM2.5'].fillna(df2['PM2.5'].mean())

17374     16.140000
2117       0.160000
18360    120.880000
24153    104.170000
22815     60.333333
1474      75.490000
21380     77.390000
29365     42.170000
25299     72.280000
17691     34.320000
Name: PM2.5, dtype: float64

In [45]:
df2.fillna({'PM2.5':df2['PM2.5'].mean(),'PM10':df2['PM10'].mean()})

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
17374,Jaipur,2019-08-10,16.140000,35.130,6.77,8.97,13.40,24.65,0.51,10.69,24.24,0.15,2.41,NaN,48.0,Good
2117,Aizawl,2020-06-27,0.160000,3.160,11.69,0.07,15.41,22.42,0.02,1.08,1.29,NaN,NaN,NaN,19.0,Good
18360,Jorapokhar,2019-02-08,120.880000,211.960,9.60,10.56,NaN,6.28,NaN,130.00,16.21,NaN,NaN,NaN,289.0,Poor
24153,Patna,2016-03-16,104.170000,79.868,12.81,19.89,22.09,NaN,1.17,6.99,29.60,0.15,0.62,0.25,241.0,Poor
22815,Mumbai,2017-08-18,60.333333,79.868,NaN,NaN,NaN,NaN,0.00,NaN,NaN,0.00,0.00,0.00,NaN,NaN
1474,Ahmedabad,2019-01-14,75.490000,79.868,9.04,61.80,19.74,NaN,9.04,34.03,80.26,4.16,32.44,7.03,407.0,Severe
21380,Lucknow,2019-03-15,77.390000,79.868,5.23,38.80,27.92,12.61,1.00,9.74,39.39,1.33,19.15,NaN,212.0,Poor
29365,Visakhapatnam,2020-01-18,42.170000,81.730,4.40,25.01,16.89,10.84,1.03,8.03,45.73,3.42,4.56,0.86,79.0,Satisfactory
25299,Patna,2019-05-06,72.280000,79.868,8.76,13.55,8.82,NaN,1.11,44.82,86.50,1.60,15.17,5.99,186.0,Moderate
17691,Jaipur,2020-06-22,34.320000,67.360,5.51,16.12,18.65,25.60,0.68,10.04,53.53,0.47,0.79,NaN,80.0,Satisfactory

In [46]:
df2.fillna(0)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
17374,Jaipur,2019-08-10,16.14,35.13,6.77,8.97,13.40,24.65,0.51,10.69,24.24,0.15,2.41,0.00,48.0,Good
2117,Aizawl,2020-06-27,0.16,3.16,11.69,0.07,15.41,22.42,0.02,1.08,1.29,0.00,0.00,0.00,19.0,Good
18360,Jorapokhar,2019-02-08,120.88,211.96,9.60,10.56,0.00,6.28,0.00,130.00,16.21,0.00,0.00,0.00,289.0,Poor
24153,Patna,2016-03-16,104.17,0.00,12.81,19.89,22.09,0.00,1.17,6.99,29.60,0.15,0.62,0.25,241.0,Poor
22815,Mumbai,2017-08-18,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0
1474,Ahmedabad,2019-01-14,75.49,0.00,9.04,61.80,19.74,0.00,9.04,34.03,80.26,4.16,32.44,7.03,407.0,Severe
21380,Lucknow,2019-03-15,77.39,0.00,5.23,38.80,27.92,12.61,1.00,9.74,39.39,1.33,19.15,0.00,212.0,Poor
29365,Visakhapatnam,2020-01-18,42.17,81.73,4.40,25.01,16.89,10.84,1.03,8.03,45.73,3.42,4.56,0.86,79.0,Satisfactory
25299,Patna,2019-05-06,72.28,0.00,8.76,13.55,8.82,0.00,1.11,44.82,86.50,1.60,15.17,5.99,186.0,Moderate
17691,Jaipur,2020-06-22,34.32,67.36,5.51,16.12,18.65,25.60,0.68,10.04,53.53,0.47,0.79,0.00,80.0,Satisfactory

In [47]:
s1 = df['Xylene'][54:64]

In [50]:
s1.fillna(method='bfill')

54    6.05
55    0.81
56    1.32
57    1.32
58    1.32
59    1.32
60    0.22
61    2.25
62    1.55
63    4.13
Name: Xylene, dtype: float64

In [51]:
s1.interpolate(method='linear')

54    6.0500
55    0.8100
56    0.9375
57    1.0650
58    1.1925
59    1.3200
60    0.2200
61    2.2500
62    1.5500
63    4.1300
Name: Xylene, dtype: float64

In [52]:
0.9375-0.81

0.12749999999999995

In [53]:
1.0650-0.9375

0.12749999999999995