In [1]:
import pandas as pd
df = pd.read_csv('C:/Develop/深圳42/data/city_day.csv')
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [9]:
df['NO'] = df['NO'].astype(object)
df['NO']

0        0.92
1        0.97
2        17.4
3         1.7
4        22.1
         ...
29526    7.68
29527    3.42
29528    3.45
29529    4.05
29530     0.4
Name: NO, Length: 29531, dtype: object

In [11]:
df['NO'] = df['NO'].astype(float)

In [14]:
df2 = df.head().copy()
df2.loc[::2,'NO'] = 'missing'

In [15]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        5 non-null      object
 1   Date        5 non-null      object
 2   PM2.5       0 non-null      float64
 3   PM10        0 non-null      float64
 4   NO          5 non-null      object
 5   NO2         5 non-null      float64
 6   NOx         5 non-null      float64
 7   NH3         0 non-null      float64
 8   CO          5 non-null      float64
 9   SO2         5 non-null      float64
 10  O3          5 non-null      float64
 11  Benzene     5 non-null      float64
 12  Toluene     5 non-null      float64
 13  Xylene      5 non-null      float64
 14  AQI         0 non-null      float64
 15  AQI_Bucket  0 non-null      object
dtypes: float64(12), object(4)
memory usage: 772.0+ bytes

In [20]:
df2['NO'].astype(float,errors='ignore')

0    missing
1       0.97
2    missing
3        1.7
4    missing
Name: NO, dtype: object

In [21]:
# 转换成数值型
pd.to_numeric(df2['NO'], errors='coerce')
# 有些时候, 应该整列都是数值的列, 由于采集/传输的原因, 导致有几值是字符串, 这会导致整列变成字符串类型, 后续计算会十分麻烦, 需要把这一列转换成数值类型
# 如果直接使用astype 要么报错, 要么不处理,此时可以使用 pd.to_numeric  可以指定errors参数为coerce 不能转换成数值的字符串会被处理成NaN

0     NaN
1    0.97
2     NaN
3    1.70
4     NaN
Name: NO, dtype: float64

## 日期时间类型

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

In [25]:
df['Date'] = pd.to_datetime(df['Date'])

In [27]:
df = pd.read_csv('C:/Develop/深圳42/data/city_day.csv',parse_dates=['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  datetime64[ns]
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: datetime64[ns](1), float64(13), object(2)
memory usage: 3.6+ MB

In [43]:
df['Date'].dt.dayofweek # 星期几 从0开始计数, 0就是星期一 6周日

0        3
1        4
2        5
3        6
4        0
        ..
29526    5
29527    6
29528    0
29529    1
29530    2
Name: Date, Length: 29531, dtype: int64

In [45]:
df['Date'].dt.weekday

0        3
1        4
2        5
3        6
4        0
        ..
29526    5
29527    6
29528    0
29529    1
29530    2
Name: Date, Length: 29531, dtype: int64

In [44]:
df['Date']

0       2015-01-01
1       2015-01-02
2       2015-01-03
3       2015-01-04
4       2015-01-05
           ...
29526   2020-06-27
29527   2020-06-28
29528   2020-06-29
29529   2020-06-30
29530   2020-07-01
Name: Date, Length: 29531, dtype: datetime64[ns]

In [47]:
df['Date'].max()

Timestamp('2020-07-01 00:00:00')

In [49]:
print(df['Date']-df['Date'].min())

0          0 days
1          1 days
2          2 days
3          3 days
4          4 days
           ...
29526   2004 days
29527   2005 days
29528   2006 days
29529   2007 days
29530   2008 days
Name: Date, Length: 29531, dtype: timedelta64[ns]

## 日期时间索引

In [88]:
df.set_index('Date', inplace=True)

In [55]:
df.sort_index(inplace=True)

In [62]:
df.loc['2018']

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
Date,,,,,,,,,,,,,,,
2018-01-01,Hyderabad,57.70,119.64,10.55,54.46,36.98,25.09,0.99,11.25,38.93,4.26,21.07,3.74,122.0,Moderate
2018-01-01,Delhi,303.41,415.09,62.76,63.92,11.79,73.16,1.80,18.58,68.75,5.72,14.77,0.24,462.0,Severe
2018-01-01,Ahmedabad,84.46,NaN,7.58,87.62,48.40,NaN,7.58,102.36,69.02,14.48,45.60,6.33,278.0,Poor
2018-01-01,Visakhapatnam,59.73,99.04,1.73,23.69,13.89,11.68,0.95,5.75,95.39,2.70,3.67,0.66,131.0,Moderate
2018-01-01,Talcher,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31,Brajrajnagar,113.28,187.85,23.93,26.53,45.54,62.13,2.70,14.50,7.55,17.54,NaN,NaN,236.0,Poor
2018-12-31,Ahmedabad,80.54,NaN,71.11,77.00,61.31,NaN,71.11,64.49,60.07,4.05,32.33,6.93,744.0,Severe
2018-12-31,Lucknow,248.51,NaN,40.06,61.89,64.70,61.30,1.01,14.70,31.43,0.08,0.90,NaN,403.0,Severe
2018-12-31,Talcher,84.30,263.09,8.80,5.94,13.73,6.03,3.25,18.03,5.67,NaN,NaN,NaN,200.0,Moderate
2018-12-31,Amritsar,78.42,186.41,31.71,33.79,59.08,9.96,0.05,2.98,5.43,9.62,2.41,9.09,184.0,Moderate

In [64]:
df.loc['2018-06-05']

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
Date,,,,,,,,,,,,,,,
2018-06-05,Ahmedabad,51.54,NaN,13.48,51.04,34.95,NaN,13.48,37.58,6.90,5.61,31.16,0.65,297.0,Poor
2018-06-05,Patna,73.28,NaN,19.86,106.35,40.32,NaN,1.14,39.36,73.29,5.98,53.75,27.67,163.0,Moderate
2018-06-05,Jaipur,79.41,225.77,7.90,12.82,18.46,14.82,0.74,9.03,70.10,0.69,1.55,NaN,210.0,Poor
2018-06-05,Chennai,42.26,NaN,10.19,22.66,17.84,28.25,0.77,6.24,34.07,0.00,3.45,NaN,86.0,Satisfactory
2018-06-05,Bengaluru,25.50,22.18,8.03,16.50,15.62,NaN,0.94,6.31,16.54,0.13,1.09,NaN,61.0,Satisfactory
2018-06-05,Jorapokhar,NaN,171.14,14.75,7.18,NaN,8.03,0.38,54.40,11.92,NaN,NaN,NaN,143.0,Moderate
2018-06-05,Kolkata,NaN,NaN,NaN,NaN,32.56,7.45,0.00,NaN,NaN,1.66,2.90,NaN,NaN,NaN
2018-06-05,Lucknow,96.54,NaN,4.19,28.77,21.61,34.00,0.58,8.05,13.17,0.00,0.00,NaN,219.0,Poor
2018-06-05,Hyderabad,31.51,67.42,3.15,30.16,18.39,14.27,0.62,7.18,48.40,0.86,5.90,1.45,83.0,Satisfactory
2018-06-05,Gurugram,69.94,134.44,17.08,24.67,35.36,NaN,0.80,1.05,40.79,0.07,NaN,NaN,162.0,Moderate
2018-06-05,Thiruvananthapuram,17.04,37.16,2.97,22.39,14.09,2.32,1.08,5.86,24.34,NaN,NaN,NaN,78.0,Satisfactory
2018-06-05,Amaravati,28.12,70.21,2.67,13.18,9.28,11.27,0.38,7.28,126.43,4.24,6.34,22.67,155.0,Moderate
2018-06-05,Brajrajnagar,50.06,97.10,4.04,10.51,14.55,10.20,2.57,12.78,15.23,3.29,NaN,NaN,107.0,Moderate
2018-06-05,Visakhapatnam,57.79,144.62,6.22,51.13,32.14,11.48,0.51,12.56,40.88,5.85,14.50,3.71,124.0,Moderate
2018-06-05,Talcher,53.57,106.84,11.37,10.98,11.98,12.93,1.85,37.53,15.38,0.00,0.00,NaN,125.0,Moderate
2018-06-05,Delhi,61.72,152.57,9.58,27.67,32.62,43.21,0.82,7.51,48.46,2.52,4.69,0.00,160.0,Moderate
2018-06-05,Amritsar,59.22,208.58,12.27,9.60,21.53,4.87,1.23,3.13,38.93,0.60,2.46,4.18,164.0,Moderate
2018-06-05,Mumbai,26.85,NaN,NaN,NaN,73.12,NaN,1.62,25.77,41.46,0.44,NaN,NaN,105.0,Moderate

In [89]:
df.index

DatetimeIndex(['2015-01-01', '2015-01-01', '2015-01-01', '2015-01-01',
               '2015-01-01', '2015-01-01', '2015-01-02', '2015-01-02',
               '2015-01-02', '2015-01-02',
               ...
               '2020-07-01', '2020-07-01', '2020-07-01', '2020-07-01',
               '2020-07-01', '2020-07-01', '2020-07-01', '2020-07-01',
               '2020-07-01', '2020-07-01'],
              dtype='datetime64[ns]', name='Date', length=29531, freq=None)

In [71]:
df.reset_index(inplace=True)

In [75]:
time_delta_series = (df['Date']-df['Date'].min())

In [78]:
time_delta_series

0          0 days
1          0 days
2          0 days
3          0 days
4          0 days
           ...
29526   2008 days
29527   2008 days
29528   2008 days
29529   2008 days
29530   2008 days
Name: Date, Length: 29531, dtype: timedelta64[ns]

In [79]:
df['time_delta']=df['Date']-df['Date'].min()

In [81]:
df.set_index('time_delta', inplace=True)

In [87]:
df.loc['20 days':'30 days']

,Date,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
time_delta,,,,,,,,,,,,,,,,
20 days,2015-01-21,Delhi,159.54,235.27,12.27,22.56,33.02,63.23,9.01,7.05,18.56,4.10,8.26,2.72,338.0,Very Poor
20 days,2015-01-21,Chennai,NaN,NaN,43.80,59.26,8.54,3.85,1.79,9.28,18.84,9.48,NaN,NaN,NaN,NaN
20 days,2015-01-21,Ahmedabad,NaN,NaN,9.52,33.56,39.28,NaN,9.52,106.93,48.75,0.33,0.00,5.65,NaN,NaN
20 days,2015-01-21,Hyderabad,NaN,NaN,12.78,18.09,30.87,NaN,0.40,2.71,5.24,0.55,4.51,0.94,NaN,NaN
20 days,2015-01-21,Mumbai,NaN,NaN,NaN,NaN,25.04,NaN,0.00,NaN,NaN,0.00,0.00,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30 days,2015-01-31,Hyderabad,NaN,NaN,6.68,28.57,35.25,NaN,0.53,5.55,31.78,0.89,7.09,1.64,NaN,NaN
30 days,2015-01-31,Delhi,158.59,207.06,30.67,41.36,57.77,67.66,8.70,5.03,17.51,4.36,8.98,2.54,334.0,Very Poor
30 days,2015-01-31,Lucknow,NaN,NaN,6.40,18.36,3.96,NaN,11.48,NaN,43.57,2.65,4.17,NaN,NaN,NaN
30 days,2015-01-31,Mumbai,NaN,NaN,NaN,NaN,27.34,NaN,0.00,NaN,NaN,0.00,0.00,0.00,NaN,NaN
30 days,2015-01-31,Bengaluru,NaN,NaN,36.24,11.11,30.07,7.77,0.46,29.18,23.21,17.23,2.92,NaN,NaN,NaN

In [84]:
df.index

TimedeltaIndex([   '0 days',    '0 days',    '0 days',    '0 days',
                   '0 days',    '0 days',    '1 days',    '1 days',
                   '1 days',    '1 days',
                ...
                '2008 days', '2008 days', '2008 days', '2008 days',
                '2008 days', '2008 days', '2008 days', '2008 days',
                '2008 days', '2008 days'],
               dtype='timedelta64[ns]', name='time_delta', length=29531, freq=None)